<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$article = $this->entity;
?>
<?php echo $this->template()->getFormattedIdentity(); ?>
<?php if($article->repository()->hasCurrentRevision()): ?>
    <?php $revision = $article->repository()->getCurrentRevision(); ?>
    <article class="article">
    	<section class="title">
	       <h2><?php echo $revision->get('title'); ?></h2>
        </section>
    	<section class="content">
            <?php echo $revision->get('content'); ?>
        </section>
    </article>
<?php endif; ?>