<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
/* @var $this->entity \Entity\Service\EntityServiceInterface */
$article = $this->entity;
if($article->repository()->hasCurrentRevision()): ?>
    <?php $revision = $article->repository()->getCurrentRevision(); ?>
    <li class="list-group-item">
    	<a
    		href="<?php echo $this->url('entity/plugin/page', array('entity' => $article->getId())); ?>">
           <?php echo $revision->get('title'); ?>
        </a>
    </li>
<?php endif; ?>