<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$article = $this->entity;
if($article->repository()->hasCurrentRevision()): ?>
    <?php $revision = $article->repository()->getCurrentRevision(); ?>
    <div class="list-group-item">
    	<a
    		href="<?php echo $this->url('entity/plugin/page', array('entity' => $article->getId())); ?>"
    		class="article">
           <?php echo $revision->get('title'); ?>
        </a>
        <?php echo $this->partial('subject/plugin/taxonomy/entity/interaction', array('entity' => $this->entity)); ?>
    </div>
<?php endif; ?>