<?php $name = $this->entity->getType()->getName(); ?>
<?php if($this->resolver('subject/plugin/taxonomy/entity/'.$name)):?>
        <?php echo $this->partial('subject/plugin/taxonomy/entity/'.$name, array('discussion' => $this->discussion, 'entity' => $this->entity, 'user' => $this->user)); ?>
    <?php else: ?>
        <?php echo $this->translate(sprintf('No view found for %s', $name)); ?>
<?php endif; ?>