<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$exercise = $this->entity;
?>
<?php if($exercise->repository()->hasCurrentRevision()): ?>
    <li class="sortable-item" data-id="<?php echo $this->entity->getId(); ?>">
        <article class="sortable-item-inner">
            <div class="pull-right btn-group">
                <a class="btn btn-default btn-xs"
                	href="<?php echo $this->url('entity/create', array('action' => 'create', 'type' => 'grouped-text-exercise'), array('query' => array('group' => array('to_entity' => $exercise->getId())))); ?>">
                	<strong>+</strong></a>
                <?php echo $this->partial('subject/plugin/taxonomy/entity/interaction', array('entity' => $this->entity)); ?>
            </div>
        	<section>
                <?php $revision = $exercise->repository()->getCurrentRevision(); ?>
                <?php echo $revision->get('content'); ?>
            </section>
        	<section>
        	   <ul class="list-group">
            	<?php foreach($exercise->exercises()->findChildren() as $child):?>
                    <li class="list-group-item">
                        <?php echo $this->partial('subject/plugin/taxonomy/entity/grouped-text-exercise', array('entity' => $child)); ?>
                    </li>
            	<?php endforeach; ?>
        	   </ul>
            </section>
        </article>
    </li>
<?php endif; ?>