<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$exercise = $this->entity;
$solution = $exercise->solution()->findChild();
?>
<?php if($exercise->repository()->hasCurrentRevision()): ?>
<article class="list-group-item">
    <?php echo $this->partial('subject/plugin/taxonomy/entity/interaction', array('entity' => $this->entity)); ?>
	<section>
        <?php $revision = $exercise->repository()->getCurrentRevision(); ?>
        <?php echo $revision->get('content'); ?>
    </section>
	<section>
    	<?php if(!is_object($solution)): ?>
    	   <?php echo sprintf($this->translate('This exercise has no solution. Do you want to add <a href="%s">one</a>?'), rawurldecode($this->url('entity/create', array('type' => 'text-solution'), array('query' => array('exercise' => array('to_entity' => $exercise->getId())))))); ?>
    	<?php else: ?>
    	<?php $solutionRepository = $solution->repository(); ?>
    	<?php if($solutionRepository->hasCurrentRevision()): ?>
    	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<?php echo $solution->getId(); ?>">
              <?php echo $this->translate('Solution'); ?>
            </a>
            <div id="<?php echo $solution->getId(); ?>" class="panel-collapse collapse">
                <?php echo $solutionRepository->getCurrentRevision()->get('content'); ?>
            </div>
        <?php elseif($solutionRepository->hasHead()): ?>
            <?php echo $this->translate('This solution is waiting for approval. It will be soon available!'); ?>
        <?php else: ?>
            <?php echo sprintf($this->translate('This exercise has no solution. Do you want to add <a href="%s">one</a>?'), $this->url('entity/plugin/repository', array('action' => 'add-revision', 'entity' => $solution->getId()))); ?>
    	<?php endif; ?>
        <?php endif; ?>
    </section>
</article>
<?php endif; ?>