<?php $solution = $this->solution; ?>
<?php $exercise = $this->exercise;?>
<?php if($solution->repository()->hasCurrentRevision() && !$solution->getTrashed()): ?>
   <article class="panel panel-default">
       <header class="panel-heading">
           <div class="row">
               <div class="col-md-10">
        	       <h4 class="panel-title">
           	           <a class="accordion-toggle" data-toggle="collapse" data-parent="#solutions-<?php echo $exercise->getId(); ?>" href="#solution-hint-<?php echo $solution->getId(); ?>"><?php echo $this->translate('Hint'); ?></a>
    	           </h4>  
	           </div>
	           <div class="col-md-2">
    	           <div class="pull-right btn-group">
                    	<a class="btn btn-default btn-xs"
                    		href="<?php echo $this->url('entity/plugin/repository',array('action' => 'add-revision', 'entity' => $solution->getId())); ?>"><span
                    		class="glyphicon glyphicon-edit"></span></a>
                    	<a class="btn btn-default btn-xs<?php echo ($solution->plugin('repository')->isUnrevised()) ? ' btn-warning' : ''?>"
                    		href="<?php echo $this->url('entity/plugin/repository',array('action' => 'history', 'entity' => $solution->getId())); ?>"><span
                    		class="glyphicon glyphicon-time"></span></a>
                    </div>
	           </div>      	               
           </div>
       </header>
       <div id="solution-hint-<?php echo $solution->getId(); ?>" class="panel-collapse collapse">
           <section class="panel-body"><?php echo $solution->repository()->getCurrentRevision()->get('hint'); ?></section>
       </div>
   </article>
   <article class="panel panel-default" id="solution-<?php echo $solution->getId(); ?>">
       <header class="panel-heading">
           <div class="row">
               <div class="col-md-10">
        	       <h4 class="panel-title">
        	           <a class="accordion-toggle" data-toggle="collapse" data-parent="#solutions-<?php echo $exercise->getId(); ?>" href="#solution-content-<?php echo $solution->getId(); ?>"><?php echo $this->translate('Solution'); ?></a>
        	       </h4>
	           </div>
	           <div class="col-md-2">
    	           <div class="pull-right btn-group">
                    	<a class="btn btn-default btn-xs"
                    		href="<?php echo $this->url('entity/plugin/repository',array('action' => 'add-revision', 'entity' => $solution->getId())); ?>"><span
                    		class="glyphicon glyphicon-edit"></span></a>
                    	<a class="btn btn-default btn-xs<?php echo ($solution->plugin('repository')->isUnrevised()) ? ' btn-warning' : ''?>"
                    		href="<?php echo $this->url('entity/plugin/repository',array('action' => 'history', 'entity' => $solution->getId())); ?>"><span
                    		class="glyphicon glyphicon-time"></span></a>
                    </div>
	           </div>      	               
           </div>
       </header>
       <div id="solution-content-<?php echo $solution->getId(); ?>" class="panel-collapse collapse">
           <section class="panel-body"><?php echo $solution->repository()->getCurrentRevision()->get('content'); ?></section>
       </div>
   </article>
<?php elseif($solution->repository()->hasHead()): ?>
    <?php echo $this->translate('This solution is waiting for approval. It will be soon available!'); ?>
<?php else: ?>
    <?php echo sprintf($this->translate('This exercise has no solution. Do you want to add <a href="%s">one</a>?'), $this->url('entity/plugin/repository', array('action' => 'add-revision', 'entity' => $solution->getId()))); ?>
<?php endif; ?>