<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="row-fluid">
    <?php $this->form->prepare(); ?>
    <?php echo $this->form()->openTag($this->form); ?>
    <div class="col-xs-4">
    <?php
        echo $this->forminput($this->form->get('id'));
        echo $this->forminput($this->form->get('parent'));
        echo $this->forminput($this->form->get('weight'));
        echo $this->forminput($this->form->get('taxonomy'));
        echo $this->formRow($this->form->get('term')->get('name'));
    ?>
    </div>
    <div class="col-xs-4">
    <?php 
        echo $this->formSubmit($this->form->get('submit'));
        echo $this->forminput($this->form->get('reset'));
    ?></div>
    <?php echo $this->form()->closeTag();?>
</div>