<div class="page-header">
    <h1><?php echo $this->translate('Sort entities'); ?> <small><?php echo $this->term->getName();?></small></h1>
</div>
<div class="sortable" data-depth="1" data-active="false" data-action="<?php echo $this->url('taxonomy/term/sort-associated', array('term' => $this->term->getId(), 'association' => $this->association)); ?>">
    <ol class="sortable-list">
        <?php foreach($this->associations as $associated):?>
            <li class="sortable-item" data-id="<?php echo $associated->getId(); ?>">
                <span class="sortable-handle"></span>
                <div class="sortable-item-inner">
                    <?php $template = $this->term->getTemplateForAssociation($this->association); ?>
                    <?php if($this->association === 'entities'): ?>
                        <?php echo $this->partial($template, array('entity' => $associated)); ?>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
    <div class="sortable-actions">
        <button class="btn btn-default sortable-activate-action"><?php print $this->translate('Sort'); ?></button>
        <button class="btn btn-success sortable-save-action is-hidden"><?php print $this->translate('Save new order'); ?></button>
        <button class="btn btn-default sortable-abort-action is-hidden"><?php print $this->translate('Cancel'); ?></button>
    </div>
</div>