<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <?php foreach($this->objects as $object): ?>
        <?php if($this->normalize()->possible($object)): ?>
            <url>
                <loc><?php echo $this->normalize()->toUrl($object, true); ?></loc>
            </url>
        <?php endif; ?>
    <?php endforeach; ?>
</urlset>