<li role="presentation"
	class="<?php $this->notification->getSeen() ? '' : 'active ' ?>"><a
	role="menuitem" tabindex="-1"
	href="<?php echo $this->url('uuid/router', array('uuid' => $this->notification->getObjects()->current()->getId())); ?>">
    <?php echo sprintf($this->translate('User %s created new content on a resource you are following.'), $this->notification->getActors()->current()->getUsername(), $this->notification->getObjects()->current()->getId(), $this->notification->getReferences()->current()->getId()); ?>
</a></li>