<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity; ?>
<?php $revision = $entity->getCurrentRevision(); ?>
<article class="content">
    <header>
        <?php echo $this->partial('entity/view/partials/actions/big', array('entity' => $entity)); ?>
    </header>
    <?php echo $this->markdown()->toHtml($revision->get('content')); ?>
    <hr>
    <?php echo $this->partial('entity/view/partials/discussions', array('entity' => $entity)); ?>
</article>