<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity; ?>
<?php $name = $entity->getType()->getName(); ?>
<?php if($this->resolver('entity/view/'.$name)):?>
        <?php echo $this->partial('entity/view/'.$name, array('discussion' => $this->discussion, 'entity' => $entity, 'hideActions' => $this->hideActions)); ?>
    <?php else: ?>
        <?php echo $this->translate(sprintf('No view found for %s', $name)); ?>
<?php endif; ?>