<?php $solution = $this->entity; ?>
<?php $hasHint = strlen($solution->repository()->getCurrentRevision()->get('hint')) > 0; ?>
<?php if($solution->repository()->hasCurrentRevision() && !$solution->getTrashed()): ?>
    <article class="panel-group collapse" id="solution-<?php echo $solution->getId(); ?>">
        <?php if($hasHint): ?>
            <section class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#solutions-<?php echo $solution->getId(); ?>" href="#solution-hint-<?php echo $solution->getId(); ?>"><?php echo $this->translate('Hint'); ?></a>
                    </h4>
                </div>
                <div id="solution-hint-<?php echo $solution->getId(); ?>" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <?php echo $solution->repository()->getCurrentRevision()->get('hint'); ?>
                    </div>
                </div>
            </section>
        <?php endif; ?>
        <section class="panel panel-default">
            <div class="panel-heading">
                <div class="pull-right btn-group">
                    <?php echo $this->partial('entity/view/partials/actions', array('entity' => $this->entity)); ?>
                </div>
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#solutions-<?php echo $solution->getId(); ?>" href="#solution-content-<?php echo $solution->getId(); ?>"><?php echo $this->translate('Solution'); ?></a>
                </h4>
            </div>
            <div id="solution-content-<?php echo $solution->getId(); ?>" class="panel-collapse collapse<?php echo $hasHint ? '' : ' in'?>">
                <div class="panel-body">
                    <?php echo $solution->repository()->getCurrentRevision()->get('content'); ?>
                </div>
            </div>
        </section>
    </article>
<?php elseif($solution->repository()->hasHead()): ?>
    <?php echo $this->translate('This solution is waiting for approval. It will be soon available!'); ?>
<?php else: ?>
    <?php echo sprintf($this->translate('This solution has no content. Do you want to create %sone%s?'), '<a href="' . $this->url('entity/plugin/repository/add-revision', ['entity' => $solution->getId()] ). '">', '</a>'); ?>
<?php endif; ?>