<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity; ?>
<?php $exercise = $this->entity; ?>
<?php $solution = $entity->getChildren('link', 'text-solution')->first(); ?>
<?php if($exercise->hasCurrentRevision()): ?>
    <article>
        <div class="pull-right btn-group">
    	   <?php if(is_object($solution)): ?>
               <a class="btn-default btn btn-xs accordion-toggle" data-toggle="collapse" data-parent="#solutions-<?php echo $solution->getId(); ?>" href="#solution-<?php echo $solution->getId(); ?>">=</a>
    	   <?php endif; ?>
           <?php echo $this->partial('entity/view/partials/actions', array('entity' => $this->entity)); ?>
        </div>
    	<section>
            <?php $revision = $exercise->getCurrentRevision(); ?>
            <?php echo $revision->get('content'); ?>
        </section>
    	<?php if(is_object($solution)): ?>
    	    <section class="panel-group" id="solutions-<?php echo $solution->getId(); ?>">
        	   <?php echo $this->partial('entity/view/default',array('entity' => $solution, 'hideActions' => array('detail', 'taxonomy'))); ?>
            </section>
        <?php endif; ?>
    </article>
<?php endif; ?>