<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity; ?>
<article>
    <section class="row">
        <div class="col-md-8">
            <?php if ($entity->hasCurrentRevision()): ?>
                <?php
                $content = $entity->getCurrentRevision()->get('content');
                echo $this->markdown()->toHtml($content);
                ?>
            <?php endif; ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->partial('entity/view/partials/actions/small', array('entity' => $this->entity)); ?>
        </div>
    </section>
    <?php foreach ($entity->getChildren('link', 'grouped-text-exercise') as $index => $child): ?>
        <section class="row">
            <div class="col-xs-1">
                <em><?php echo $this->toAlpha($index); ?>) </em>
            </div>
            <div class="col-xs-11">
                <?php echo $this->partial('entity/view/default', array('entity' => $child, 'parent' => $entity)); ?>
                <hr>
            </div>
        </section>
    <?php endforeach; ?>
</article>
<hr>