<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity; ?>
<article>
    <section>
        <?php if($entity->hasCurrentRevision()): ?>
            <?php echo $this->markdown()->toHtml($entity->getCurrentRevision()->get('content')); ?>
        <?php endif; ?>
    </section>
    <section class="clearfix">
        <?php echo $this->partial('entity/view/partials/actions/small', array('entity' => $this->entity)); ?>
        <div class="sortable" data-action="<?php echo $this->url('entity/link/order', array('type' => 'link', 'entity' => $entity->getId())); ?>" data-depth="1" data-active="false">
            <ol class="sortable-list">
                <?php foreach($entity->getChildren('link', 'grouped-text-exercise') as $child): ?>
                    <li class="sortable-item" data-id="<?php echo $child->getId(); ?>">
                        <span class="sortable-handle"></span>
                        <div class="sortable-item-inner">
                            <?php echo $this->partial('entity/view/default', array('entity' => $child, 'parent' => $entity)); ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="sortable-actions pull-right btn-group">
                <?php echo $this->partial('entity/view/partials/sortable-actions'); ?>
            </div>
        </div>
    </section>
</article>