<?php
/* @var $entity \Entity\Entity\EntityInterface */
$entity = $this->entity;
$exercise = $this->entity;
$solution = $entity->getChildren('link', 'text-solution')->first();
if(!is_object($solution) || !$solution->hasCurrentRevision() || $solution->getTrashed()) {
    $solution = null;
} else {
    $revision = $solution->getCurrentRevision();
    $hintContent = $revision->get('hint');
    $hintContent = trim($this->markdown()->toHtml($hintContent));
    $solutionContent = trim($revision->get('content'));
    $solutionContent = trim($this->markdown()->toHtml($solutionContent));
}
?>
<?php if($exercise->hasCurrentRevision()): ?>
    <article>
    	<section class="row">
            <div class="col-sm-8">
                <?php $revision = $exercise->getCurrentRevision(); ?>
                <?php echo $this->markdown()->toHtml($revision->get('content')); ?>
            </div>
            <div class="col-sm-4">
                <ul class="nav nav-pills">
                    <?php if($solution): ?>
                        <?php if($hintContent): ?>
                            <li>
                                <a data-toggle="collapse" data-parent="#solutions-<?php echo $solution->getId(); ?>" href="#hint-<?php echo $solution->getId(); ?>">
                                    <span class="glyphicon glyphicon-question-sign"></span>
                                </a>
                            </li>
                        <?php endif; ?>
                        <li>
                            <a data-toggle="collapse" data-parent="#solutions-<?php echo $solution->getId(); ?>" href="#solution-<?php echo $solution->getId(); ?>">
                                <span class="glyphicon glyphicon-exclamation-sign"></span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php echo $this->partial('entity/view/partials/actions/small-essential', array('entity' => $this->entity)); ?>
                </ul>
            </div>
        </section>
    	<?php if($solution): ?>
            <?php echo $this->partial('entity/view/default',array('entity' => $solution)); ?>
        <?php endif; ?>
    </article>
<?php endif; ?>