<?php
/* @var $entity \Entity\Entity\EntityInterface */
$entity = $this->entity;
$solution = $entity;
$revision = $solution->getCurrentRevision();
$hintContent = $revision->get('hint');
$hintContent = $this->markdown()->toHtml($hintContent);
$solutionContent = $revision->get('content');
$solutionContent = $this->markdown()->toHtml($solutionContent);
?>
<article>
    <?php if($hintContent): ?>
        <section class="collapse" id="hint-<?php echo $solution->getId(); ?>">
            <div class="row">
                <div class="col-xs-9">
                    <h5>
                        <span class="glyphicon glyphicon-question-sign"></span> <?php echo $this->translate('Hint'); ?>
                    </h5>
                </div>
                <div class="col-xs-3">
                    <?php echo $this->partial('entity/view/partials/actions/small', array('entity' => $solution)); ?>
                </div>
            </div>
            <hr>
            <?php echo $hintContent; ?>
        </section>
    <?php endif; ?>
    <section class="collapse" id="solution-<?php echo $solution->getId(); ?>">
        <div class="row">
            <div class="col-xs-9">
                <h5>
                    <span class="glyphicon glyphicon-exclamation-sign"></span> <?php echo $this->translate('Solution'); ?>
                </h5>
            </div>
            <div class="col-xs-3">
                <?php echo $this->partial('entity/view/partials/actions/small', array('entity' => $solution)); ?>
            </div>
        </div>
        <hr>
        <?php echo $solutionContent; ?>
    </section>
</article>