<?php $revision = $this->entity->plugin('repository')->getCurrentRevision();?>
<article>
	<header>
		<div class="pull-right btn-group">
            <?php echo $this->partial('entity/view/partials/actions', array('entity' => $this->entity, 'hide' => $this->hideActions)); ?>
        </div>
	</header>
	<section>
        <?php echo $this->partial('entity/plugin/page/video/youtube', array('content' => $revision->get('content'), 'discussion' => $this->discussion, 'entity' => $this->entity, 'user' => $this->user)); ?>
    </section>
	<hr>
	<section>
        <?php echo $this->partial('entity/view/partials/discussions', array('entity' => $this->entity)); ?>
    </section>
</article>