<?php foreach($this->term->getChildren() as $term): ?>    	
    <h4>
                FIXME
        <a class="" href="<?php //echo rawurldecode($this->url('subject/taxonomy', array('subject' => $this->subject->getSlug(), 'path' => $this->plugin->getPathToTermAsUri($term)))); ?>">
            <?php echo $term->getName(); ?>
        </a>
    </h4>	    
    <div class="list-group">
        <?php foreach($term->getAssociated('entities') as $entity): ?>
            <?php if(!$entity->getTrashed()): ?>
                <?php echo $this->partial('subject/plugin/taxonomy/entity/default', array('entity' => $entity)); ?>
            <?php endif; ?>
        <?php endforeach;?>
    </div>
<hr>
<?php endforeach; ?>