<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$table = [[],[],[],[]];
?>
<div class="row">
    <div class="col-md-9">
        <?php if($this->term->getDescription()): ?>
            <em><?php echo $this->term->getDescription(); ?></em>
        <?php endif;?>
    </div>
    <div class="col-md-3">
        <div class="btn-group pull-right">
            <?php if ($this->isGranted('entity.create') && $this->isGranted(
                    'taxonomy.term.associate',
                    $this->term
                )
            ): ?>
                <div class="btn-group">
                    <a class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" href="#">
                         <span class="glyphicon glyphicon-file"></span> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach($this->subject()->getOptions($this->subject)->getAllowedEntities() as $type):?>
                            <li>
                                <a href="<?php echo $this->url('entity/create', array('type' => $type), array('query' => array( 'taxonomy' => array( 'term' => $this->term->getId())))); ?>">
                                   <?php echo $this->translate($type);?>
                               </a>
                           </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <?php if ($this->isGranted('taxonomy.term.associated.sort', $this->term)): ?>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('taxonomy/term/sort-associated', array('association' => 'entities', 'term' => $this->term->getId())); ?>">
                     <span class="glyphicon glyphicon-sort"></span>
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>
<hr>
<div class="entities">
    <?php foreach($this->links as $link): ?>
        <?php $partial = $this->partial('subject/taxonomy/entity/default', array('entity' => $link)); ?>
        <?php if(!strlen(trim($partial))) continue; ?>
        <?php switch($link->getType()->getName()){
            case 'article': $table[0][] = $partial; break; ?>
            <?php case 'video': $table[1][] = $partial; break; ?>
            <?php case 'module': $table[2][] = $partial; break; ?>
            <?php default: $table[3][] = $partial; break;?>
        <?php } ?>
    <?php endforeach; ?>
    <?php for($i = 0; $i < 3; $i++): ?>
        <!-- Render articles, videos and courses iteratively -->
        <?php if(count($table[$i])): ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>
                        <?php switch($i):
                            case 0: ?>
                                <span class="glyphicon glyphicon-book"></span> <?php echo $this->translate('Articles'); ?>
                            <?php break;
                            case 1: ?>
                                <span class="glyphicon glyphicon-facetime-video"></span> <?php echo $this->translate('Videos'); ?>
                            <?php break;
                            case 2: ?>
                                <span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Modules'); ?>
                        <?php endswitch; ?>
                    </h4>
                </div>
                <hr>
                <?php foreach($table[$i] as $index => $row): ?>
                    <?php if($index % 3 == 0): ?>
            </div>
            <hr>
            <div class="row">
                    <?php endif; ?>
                    <div class="col-sm-4">
                        <?php echo $row; ?>
                    </div>
                <?php endforeach; ?>
            </div>
            <hr>
        <?php endif; ?>
    <?php endfor; ?>
    <hr>
    <?php if(count($table[3])): ?>
        <h4><span class="glyphicon glyphicon-ok-sign"></span> <strong><?php echo $this->translate('Exercises'); ?></strong></h4>
        <hr>
        <?php foreach($table[3] as $index => $row): ?>
            <div class="row">
                <div class="col-xs-1">
                    <strong><?php echo $index + 1; ?>.</strong>
                </div>
                <div class="col-xs-11">
                    <?php echo $row; ?>
                </div>
            </div>
            <hr>
        <?php endforeach; ?>
    <?php endif; ?>
</div>