<?php
$user   = $this->normalize()->toAnchor($this->event->getActor());
$term   = $this->normalize()->toAnchor($this->event->getObject());
$object = $this->event->getParameter('object');
if ($object) {
    $object = $this->normalize()->toAnchor($object);
} else {
    $object = '<strong>' . $this->translate('removed content') . '</strong>';
}
echo sprintf($this->translate('%s associated %s with taxonomy %s'), $user, $object, $term);