<?php $this->layout('layout/1-col'); ?>

    <br>

<div class="jumbotron">
    <h1><?php echo $this->translate('Forbidden'); ?></h1>

    <p><?php echo $this->translate('It looks like you went somewhere you weren\'t supposed to be.'); ?></p>

    <p><a href="<?php echo $this->url('home'); ?>" class="btn btn-primary btn-lg" role="button">
            <?php echo $this->translate('Take the blue pill and return home'); ?>
        </a>
    </p>

    <p></p>
</div>