<?php
/**
* @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg
* 
* renders first level menu items as 1of6 columns
*/
$html = array(
    '<div class="row-fluid">',
);

foreach ($this->container as $page) {

    if (! $page->isVisible() || !$this->navigation()->accept($page)) {
        continue;
    }

    $html[] = '<div class="col-xs-2">';
    $html[] = '<div class="inner">';
    $html[] = '<ul class="nav">';
    // header
    $html[] = '<li class="nav-header">';
    $html[] = '<a href="' . $page->getHref() . '">';
    if ($page->get('icon')) {
        $html[] = '<i class="icon-' . $page->get('icon') . '"></i>';
    }
    $html[] = $page->getLabel();
    $html[] = "</a>";
    $html[] = "</li>";
    
    if (! empty($page->pages)) {

        foreach ($page->pages as $subpage) {
            // visibility of the sub-page
            if (! $subpage->isVisible()) {
                continue;
            }
            if ($subpage->getLabel() == 'divider') {
                $html[] = '<li class="divider"></li>';
                continue;
            }
            $html[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
            $html[] = '<a href="' . $subpage->getHref() . '">';
            
            if ($subpage->get('icon')) {
                $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
            }
            
            $html[] = $subpage->getLabel();
            $html[] = "</a>";
            $html[] = "</li>";
        }
    }

    $html[] = '</ul>';
    $html[] = '</div>';
    $html[] = '</div>';
}

$html[] = '</div>';

echo join(PHP_EOL, $html);