<?php
/**
 * @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg; Timo Klement
 */
$html = array();
//$html[] = '<div class="navbar navbar-fixed-top">';
//$html[] = ' <div class="navbar-inner">';
//$html[] = ' <div class="container">';
$html[] = ' <div class="row ' . $this->navigation()->menu()->getUlClass() . '">';

foreach ($this->container as $page) {

    // visibility of the page
    if (!$page->isVisible() || !$this->navigation()->accept($page)) {
        continue;
    }

    // li-element without subpages
    $html[] = '<div class="col-xs-4">';
    $html[] = '<a href="' . $this->alias($page->getHref()) . '">';
    if ($page->get('icon')) {
        $html[] = '<i class="glyphicon glyphicon-' . $page->get('icon') . '"></i>';
    }
    $html[] = $this->translate($page->getLabel());
    $html[] = '</a>';

    $html[] = "</div>";
}

$html[] = '</div>';

echo join(PHP_EOL, $html);