<?php
/**
* @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg; Timo Klement
*/
$html = array();
//$html[] = '<div class="navbar navbar-fixed-top">';
//$html[] = ' <div class="navbar-inner">';
//$html[] = ' <div class="container">';
$html[] = ' <ul class="' . $this->navigation()->menu()->getUlClass() . '">';

foreach ($this->container as $page) {
    // visibility of the page
    if (! $page->isVisible()) {
        continue;
    }
    
    // dropdown
    $dropdown = ! empty($page->pages);
    
    // check for subpages
    // if exists, insert a dropdown class and a data-toggle attribute
    // if not exists, let the <li>-attribute and <a>-attribute empty
    if (count($page->_pages) > 0) {
        // li-element with subpages
        $html[] = '<li' . ($dropdown ? ' class="dropdown"' : '') . '>';
        $html[] = '<a href="' . ($dropdown ? '#' : $page->getHref()) . '" ' . 'class="dropdown-toggle" data-toggle="dropdown">';
        $html[] = $page->getLabel();
        
        if ($dropdown) {
            $html[] = '<b class="caret"></b>';
        }
        
        $html[] = '</a>';
    } else {
        // li-element without subpages
        $html[] = '<li>';
        $html[] = '<a href="' . $page->getHref() . '">';
        $html[] = $page->getLabel();
        $html[] = '</a>';
    }
    
    if (! $dropdown) {
        $html[] = '</li>';
        continue;
    }
    
    $html[] = '<ul class="dropdown-menu">';
    
    foreach ($page->pages as $subpage) {
        // visibility of the sub-page
        if (! $subpage->isVisible()) {
            continue;
        }
        if ($subpage->getLabel() == 'divider') {
            $html[] = '<li class="divider"></li>';
            continue;
        }
        $html[] = '<li class="' . ($subpage->isActive() ? 'active' : '') . (count($subpage->_pages) != 0 ? ' dropdown-submenu' : '') .'">';
        $html[] = '<a href="' . $subpage->getHref() . '">';
        
        if ($subpage->get('icon')) {
            $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
        }
        $html[] = $subpage->getLabel();
        $html[] = "</a>";
        
        if(count($page->_pages)){
            $html[] = '<ul class="dropdown-menu">';
            foreach ($subpage->pages as $level3) {
                if (! $level3->isVisible()) {
                    continue;
                }
                if ($level3->getLabel() == 'divider') {
                    $html[] = '<li class="divider"></li>';
                    continue;
                }
                $html[] = '<li class="' . ($level3->isActive() ? 'active' : '').'">';
                $html[] = '<a href="' . $level3->getHref() . '">';
                
                if ($level3->get('icon')) {
                    $html[] = '<i class="icon-' . $level3->get('icon') . '"></i>';
                }
                $html[] = $level3->getLabel();
                $html[] = "</a>";
                $html[] = "</li>";
            }
            $html[] = '</ul>';
        }
        $html[] = "</li>";
    }
    
    $html[] = "</ul>";
    $html[] = "</li>";
}

$html[] = '</ul>';
//$html[] = '</div>';
//$html[] = '</div>';
//$html[] = '</div>';

echo join(PHP_EOL, $html);