<?php
/**
* @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg; Timo Klement
*/

$activeSubject = '';
$html = array();

foreach ($this->container as $page) {
    if ($page->isActive(true)) {
        $activeSubject = $page->getLabel();
    }

    $html[] = '<div class="row">';
    $html[] = '<div class="col-xs-5">';
    $html[] = '<h4 class="is-bold">' . $page->getLabel() . '</h4>';
    $html[] = '</div>';
    $html[] = '<div class="col-xs-7">';

    if(! empty($page->pages)) {
        $html[] = '<ul class="nav">';
        $html[] = $this->partial('layout/navigation/partial/nested-navigation-list', array('pages' => $page->pages));
        $html[] = "</ul>";
        if ($page->isActive(true)) {
            $activeSubject = $this->partial('layout/navigation/partial/active-subject', array('subject' => $activeSubject, 'pages' => $page->pages));
        }
    }

    $html[] = '</div>';
    $html[] = '</div>';
} ?>
<div class="dropdown is-inline-block">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <?php echo $activeSubject; ?>
    <b class="caret"></b></a>
    <div class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <?php 
        echo join(PHP_EOL, $html);
    ?>
    </div>
</div>