<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="page-header">
    <h1><?php echo $this->translate('Roles'); ?></h1>
</div>
<div class="list-group">
<?php foreach($this->roles as $role): ?>
    <a class="list-group-item" href="<?php echo $this->url('users/role', array('role' => $role->getId())); ?>">
        <h4 class="list-group-item-heading"><?php echo $role->getName(); ?></h4>
        <p class="list-group-item-text"><?php echo $role->getDescription(); ?></p>
    </a>
<?php endforeach; ?>
</div>