<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<h1 class="page_header"><?php echo $this->translate('Benutzerrollen'); ?></h1>
<?php foreach($this->roles as $role):?>
<ul>
    <li><a href="<?php echo $this->url('users/role', array('role' => $role->getId())); ?>"><?php echo $role->getName(); ?></a></li>
</ul>
<?php endforeach; ?>