<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="pull-right btn-group">
	<div class="btn-group group-dropdown">
		<a class="btn btn-default btn-xs dropdown-toggle"
			data-toggle="dropdown" href="#">  <span class="glyphicon glyphicon-plus"></span>
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
            <?php foreach($this->taxonomy()->getOptions($this->term)->getAllowedChildren() as $taxonomy):?>
                <li><a
				href="<?php echo $this->url('taxonomy/term/create', array('taxonomy' => $taxonomy, 'parent' => $this->term->getId())); ?>"><?php echo $taxonomy; ?></a></li>
            <?php endforeach;?>
		</ul>
	</div>
	<a href="<?php echo $this->url('taxonomy/term/action',array('action' => 'update', 'id' => $this->term->getId() )); ?>"
		class="btn btn-default btn-xs"><i class="glyphicon glyphicon-pencil"></i></a>
    <a class="btn btn-default btn-xs" href="<?php echo $this->url('event/history',array('id' => $this->term->getId())); ?>"><span
    	class="glyphicon glyphicon-hdd"></span></a>
	<?php if($this->term->isTrashed()): ?>
    	<a href="<?php echo $this->url('uuid/restore',array('id' => $this->term->getId() )); ?>"
    		class="btn btn-warning btn-xs">
    		<span class="glyphicon glyphicon-refresh"></span>
    	</a>
	<?php else: ?>
    	<a href="<?php echo $this->url('uuid/trash',array('id' => $this->term->getId() )); ?>"
    		class="btn btn-default btn-xs">
    		<span class="glyphicon glyphicon-trash"></span>
    	</a>
	<?php endif; ?>
</div>