<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="pull-right btn-group">
	<div class="btn-group group-dropdown">
		<a class="btn btn-default btn-xs dropdown-toggle"
			data-toggle="dropdown" href="#">  <span class="glyphicon glyphicon-plus"></span>
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
            <?php foreach($this->term->getAllowedChildrenTypes() as $taxonomy):?>
                <li><a
				href="<?php echo $this->url('taxonomy/term/create', array('taxonomy' => $taxonomy->getId(), 'parent' => $this->term->getId())); ?>"><?php echo $taxonomy->getName(); ?></a></li>
            <?php endforeach;?>
		</ul>
	</div>
	<a
		href="<?php echo $this->url('taxonomy/term/action',array('action' => 'update', 'id' => $this->term->getId() )); ?>"
		class="btn btn-default btn-xs"><i class="glyphicon glyphicon-pencil"></i></a>
</div>