<?php
/**
 *
* Athene2 - Advanced Learning Resources Manager
*
* @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
* @license	LGPL-3.0
* @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
* @link		https://github.com/serlo-org/athene2 for the canonical source repository
* @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
*/
$classes = array();

if (! isset($this->isChild)) : ?>
    <div class="panel">
        <div class="panel-body">
            <?php echo $this->partial('taxonomy/term/organize/actions', array('term' => $this->term)); ?>
        </div>
    </div>
    <div class="sortable" data-depth="0" data-active="false" data-action="<?php echo $this->url('taxonomy/term/order', array('term' => $this->term->getId())); ?>">
        <div class="sortable-actions">
    		<button class="btn btn-default sortable-activate-action"><?php print $this->translate('Sort'); ?></button>
            <button class="btn btn-success sortable-save-action is-hidden"><?php print $this->translate('Save new order'); ?></button>
            <button class="btn btn-default sortable-abort-action is-hidden"><?php print $this->translate('Cancel'); ?></button>
        </div>
<?php endif; ?>
        <ol id="<?php echo $this->term->getId(); ?>" class="sortable-list"
    		data-id="<?php echo $this->term->getId(); ?>">
            <?php foreach($this->term->getChildren() as $term):?>
                <li class="sortable-item" data-id="<?php echo $term->getId(); ?>">
                    <span class="sortable-handle"></span>
                    <div class="sortable-item-inner">
                        <?php echo $term->getName(); ?>
                        <?php echo $this->partial('taxonomy/term/organize/actions', array('term' => $term)); ?>
                    </div>
                    <?php echo $this->partial('taxonomy/term/organize/partial', array('term' => $term, 'isChild' => true)); ?>
                </li>
            <?php endforeach; ?>
        </ol>
<?php if (!isset($this->isChild) && $this->rbac()->hasAccessToRoute('taxonomy/term/order')) : ?>
        <div class="sortable-actions">
    		<button class="btn btn-default sortable-activate-action"><?php print $this->translate('Sort'); ?></button>
            <button class="btn btn-success sortable-save-action is-hidden"><?php print $this->translate('Save new order'); ?></button>
            <button class="btn btn-default sortable-abort-action is-hidden"><?php print $this->translate('Cancel'); ?></button>
    	</div>
    </div>
<?php endif; ?>