<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license     LGPL-3.0
 * @license     http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$classes = array();

if (!isset($this->isChild)) : ?>
    <div class="pull-right btn-group">
        <div class="btn-group group-dropdown">
            <a class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="glyphicon glyphicon-plus"></span> <span class="caret"></span> </a>
            <ul class="dropdown-menu">
                <?php foreach ($this->taxonomy()->getOptions($this->term)->getAllowedChildren() as $taxonomy): ?>
                    <li><a href="<?php echo $this->url(
                            'taxonomy/term/create',
                            array('taxonomy' => $taxonomy, 'parent' => $this->term->getId())
                        ); ?>"><?php echo $taxonomy; ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <h3><?php echo $this->term->getName(); ?></h3>
    <hr>
    <div class="sortable" data-active="false" data-action="<?php echo $this->url(
        'taxonomy/term/order',
        array('term' => $this->term->getId())
    ); ?>">
<?php endif; ?>
    <ol class="sortable-list" data-id="<?php echo $this->term->getId(); ?>">
        <?php foreach ($this->term->getChildren() as $term): ?>
            <li class="sortable-item" data-id="<?php echo $term->getId(); ?>">
                <span class="sortable-handle"></span>

                <div class="sortable-item-inner">
                    <?php echo $term->getName(); ?>
                    <?php echo $this->partial('taxonomy/term/organize/actions', array('term' => $term)); ?>
                </div>
                <?php echo $this->partial(
                    'taxonomy/term/organize/partial',
                    array('term' => $term, 'isChild' => true)
                ); ?>
            </li>
        <?php endforeach; ?>
    </ol>
<?php if (!isset($this->isChild) && $this->isGranted('taxonomy.term.sort', $this->term)): ?>
    <div class="panel panel-default clearfix">
        <div class="panel-heading">
            <h5 class="panel-title"><?php echo $this->translate('Tools'); ?></h5>
        </div>
        <div class="sortable-actions pull-right panel-body">
            <button class="btn btn-default sortable-activate-action"><?php print $this->translate('Sort'); ?></button>
            <button class="btn btn-success sortable-save-action is-hidden"><?php print $this->translate(
                    'Save new order'
                ); ?></button>
            <button class="btn btn-default sortable-abort-action is-hidden"><?php print $this->translate(
                    'Cancel'
                ); ?></button>
        </div>
    </div>
    </div>
<?php endif; ?>