<?php
/* @var $entity \Entity\Entity\EntityInterface */
/* @var $options \Entity\Options\EntityOptions */
$entity = $this->entity;
$options = $this->entity()->getOptions($entity);

if ($this->isGranted('entity.event.history', $entity)): ?>
    <li>
        <a href="<?php echo $this->url('event/history', array('id' => $entity->getId())); ?>">
            <span class="glyphicon glyphicon-hdd"></span>
            <?php echo $this->translate('Show logfile'); ?>
        </a>
    </li>
<?php endif; ?>