<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$name = 'none';
if(is_object($this->term)) {
    $name = $this->term->getTaxonomy()->getName();
}
$template = 'subject/taxonomy/templates/' . $name;
$data = array(
    'links' => $this->links,
    'subject' => $this->subject,
    'term' => $this->term,
    'terms' => $this->terms
);
?>
<?php if(is_object($this->term) && $this->term->isTrashed()): ?>
    <div class="alert alert-danger"><?php echo $this->translate('This taxonomy term is marked as <strong>trashed</strong>. Contents might be out of date or unmaintained.'); ?></div>
<?php endif; ?>
<?php if($this->resolver($template)):?>
    <?php echo $this->partial($template, $data); ?>
<?php else: ?>
    <?php echo $this->partial('subject/taxonomy/templates/partials/entities', array('links' => $this->links, 'subject' => $this->subject, 'term' => $this->term)); ?>
    <?php echo $this->partial('subject/taxonomy/templates/partials/branches', array('links' => $this->links, 'subject' => $this->subject, 'term' => $this->term)); ?>
<?php endif; ?>
<hr>
<?php if(is_object($this->term)): ?>
    <?php echo $this->discussion($this->term->getUuidEntity())->findForum([$this->subject->getSlug(), $this->term->getTaxonomy()->getName()])->render(); ?>
<?php endif; ?>