<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Jakob Pfab (jakob.pfab@serlo.org)
 * @license     LGPL-3.0
 * @license     http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 */
namespace Cache\Strategy;

use StrokerCache\Strategy\Route;
use Zend\Authentication\AuthenticationService;
use Zend\Mvc\MvcEvent;

class RouteStrategy extends Route
{
    public function shouldCache(MvcEvent $event)
    {

        $app            = $event->getApplication();
        $serviceManager = $app->getServiceManager();
        /* @var $authenticationService AuthenticationService */
        $authenticationService = $serviceManager->get('Zend\Authentication\AuthenticationService');
        if ($authenticationService->hasIdentity()) {
            return false;
        }
        return parent::shouldCache($event); // TODO: Change the autogenerated stub
    }
}
