<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th><?php echo $this->translate('ID');?></th>
			<th><?php echo $this->translate('Titel');?></th>
			<th><?php echo $this->translate('Verknüpftes Element (uuid)');?></th>
			<th><?php echo $this->translate('Author');?></th>
			<th><?php echo $this->translate('Datum');?></th>
			<th><?php echo $this->translate('Kommentare');?></th>
		</tr>
	</thead>
	<tbody>
    <?php foreach($issues as $issue):?>
        <tr>
			<td><?php echo $issue->getId();?></td>
			<td><a href="<?php echo $this->url('issue',array('action' => 'show', 'id' => $issue->getId())); ?>"><?php echo $issue->getTitle();?></a></td>
			<td><?php echo $issue->getOn()->getUuid(); ?></td>
			<td><?php echo $issue->getAuthor()->getName();?></td>
			<td><?php echo $issue->getDate()->format($this->dateFormat()); ?></td>
			<td>0</td>
		</tr>
        <?php endforeach; ?>
    </tbody>
</table>