<?php $type = $this->entity->getType()->getName(); ?>
<?php if($this->resolver('learning-resource/view/minimalistic/'.$type)):?>
        <?php echo $this->partial('learning-resource/view/minimalistic/'.$type, array('entity' => $this->entity)); ?>
    <?php else: ?>
        <?php if($this->entity->repository()->hasCurrentRevision()): ?>
            <?php echo $this->entity->repository()->getCurrentRevision()->get('title'); ?> <small><i><?php echo $this->entity->getType()->getName(); ?></i></small>
        <?php else: ?>
            <?php echo $this->translate('Pending review:'); ?> <?php echo $this->entity->getId(); ?> <small><i><?php echo $this->entity->getType()->getName(); ?></i></small>
        <?php endif; ?>
<?php endif; ?>