<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="row-fluid">
	<div class="span9"></div>
	<div class="span3">
	    <?php if($this->acceptsEntities): ?>
		<div class="btn-group pull-right">
			<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="icon-plus"></i><?php echo $this->translate('hinzufügen');?> <span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li><a href="<?php echo $this->url('entity/common', array('action' => 'create'), array('query' => array( 'term' => $this->taxonomy->getId()))); ?>"><?php echo $this->translate('Aufgabe');?></a></li>
			</ul>
		</div>
		<?php endif; ?>
	</div>
</div>
<?php if($this->acceptsEntities): ?>
<div class="entities">
    <?php foreach($this->entities as $entity): ?>
    <div class="right btn-group">
    	<a
    		href="<?php echo $this->url('entity/plugin/topic-folder', array('action' => 'set', 'entity' => $entity->getId() )); ?>"
    		class="btn btn-mini"><i class="icon-download-alt"></i></a>
    </div>
    <?php switch($entity->getType()->getName()):
            case 'text-exercise': ?>
            <?php echo $this->partial('resource-manager/plugin/topic/exercise', array('exercise' => $entity)); ?>
            <?php break; ?>
    <?php endswitch; ?>

    <?php endforeach; ?>
</div>
<?php endif; ?>