<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$id = uniqid('sort_', true);
?>
<li class="term" data-id="<?php echo $this->term->getId(); ?>">
	<div class="" style="margin: 5px 0;">
		<?php //echo $this->partial('taxonomy/term/actions', array('term' => $this->term)); ?>
		<div>
			<a class=""
				href="<?php echo rawurldecode($this->url('subject/plugin/topic', array('subject' => $this->subject->getName(), 'path' => implode('/', $this->term->getPath())))); ?>"><?php echo $this->term->getName(); ?></a>
			(<?php echo $this->term->countEntities(); ?>)
		</div>
	</div>
	<ul class="sortable">
        <?php foreach($this->term->getChildren() as $child):?>
            <?php echo $this->partial('resource-manager/plugin/topic/partial', array('term' => $child)); ?>
        <?php endforeach; ?>
    </ul>
</li>