<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$this->renderTitle($this->translate('Issues'));
?>
<ul class="nav nav-tabs" id="myTab">
	<li class="active"><a href="#open" data-toggle="tab"><?php echo $this->translate('Offene Issues') . " ({$issues['open']->count()})"; ?></a></li>
	<li><a href="#closed" data-toggle="tab"><?php echo $this->translate('Geschlossene Issues') . " ({$issues['closed']->count()})"; ?></a></li>
</ul>

<div class="tab-content">
	<div class="tab-pane active" id="open">
		<?php echo $this->partial('issue/issue/partials/issues', array('issues' => $issues['open']));?>
	</div>
	<div class="tab-pane" id="closed">
		<?php echo $this->partial('issue/issue/partials/issues', array('issues' => $issues['closed']));?>	   
	</div>
</div>