
<?php echo $this->pageHeader('horizon')->render();?>
 

<div class="col-xs-12">
<a href="<?php echo $this->url('ads/add');?>" class="btn btn-default pull-left">
	<span class="glyphicon glyphicon-pencil"></span>
    <?php echo $this->translate('new'); ?> 
</a>
</div>
<div class="row"><div class="col-xs-12"></div>

	<?php  foreach ($this->ads as $ad) :?>
        			<div class="col-xs-3">
        			<a href="<?php echo $this->url('ads/ad/out',array('id'=>$ad->getId()));?>" >
        			<button type="button" class="btn btn-default ">
<small><a
			href="<?php echo $this->url('ads/ad/edit',array('id'=>$ad->getId()));?>"
			class="btn btn-success btn-xs pull-right"> <span
				class="glyphicon glyphicon-pencil"></span></a> <a
			href="<?php echo $this->url('ads/ad/delete',array('id'=>$ad->getId()));?>"
			class="btn btn-danger btn-xs  pull-right"><span
				class="glyphicon glyphicon-remove"></span> </a> </small> <br> <a
			href="<?php echo $ad->getUrl();?>" target="_blank">  	<?php echo $ad->getTitle();?>	</a>
		<br> <small>
 <?php
    
    echo $this->translate('frequency');
    echo ' ';
    
    for ($i = 1; $i <= 3; $i ++) {
        if ($ad->getFrequency() >= $i)
            echo '<span class="glyphicon glyphicon-star"></span>';
        else
            echo '<span class="glyphicon glyphicon-star-empty"></span>';
    }
    
    ?><br>
 <?php echo $this->translate('views'); echo ' '.$ad->getViews(); ?><br>
 <?php echo $this->translate('clicks'); echo ' '.$ad->getClicks(); ?><br>


		</small>
		<hr>
		<small> <img alt="<?php echo $ad->getTitle();?>"
			src="<?php echo $ad->getImage()->getLocation();?>"  class="img-responsive img-radio" />	<?php echo $ad->getContent();?></small>

	</div>
	
</button></a>


<?php endforeach; ?>

