<?php if ($this->revision && $this->isGranted('page.revision.create', $this->revision)): ?>
    <?php $id = $this->revision->getId(); ?>
    <!-- Only Visible for if User has Permission -->
    <div class="btn-group">
        <a href="<?php echo $this->url(
            'page/revision/create',
            array('page' => $this->page->getId(), 'revision' => $id)
        ) ?>" class="btn btn-xs btn-default">
            <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('edit'); ?>
        </a>

        <a class="btn btn-xs btn-default" href="<?php echo $this->url(
            'page/revision/view-all',
            array('page' => $this->page->getId())
        ) ?>"> <span class="glyphicon glyphicon-align-left"></span> <?php echo $this->translate('revisions'); ?>
        </a>

        <?php if ($this->revision->getRepository()->getCurrentRevision() != $this->revision): ?>
            <a href="<?php echo $this->url(
                'uuid/trash',
                array('id' => $id)
            ); ?>" class="btn btn-link"> <span class="glyphicon glyphicon-remove"></span>
                <?php echo $this->translate('trash'); ?>
            </a>

            <a href="<?php echo $this->url(
                'page/revision/checkout',
                array('repository' => $this->page->getId(), 'revision' => $id)
            ) ?>" class="btn btn-link"><span class="glyphicon glyphicon-ok">
                <?php echo $this->translate('Checkout'); ?> </a>

            <a href="<?php echo $this->url('page/view', array('repository' => $this->page->getId())); ?>"
               class="btn btn-xs btn-default"> <span class="glyphicon glyphicon-star"></span>
                <?php echo $this->translate('checkout'); ?>
            </a>
        <?php endif; ?>

    </div>
<?php endif; ?>