<?php echo $this->doctype(); ?>

<html class="fuelux" lang="en">
<head>
<meta charset="utf-8">
        <?php
        echo $this->headTitle((strlen($this->titleHead) ? $this->translate($this->titleHead) . ' - ' : '') . 'Serlo.org')
            ->setAutoEscape(false);
        ?>
        
        <?php
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
        echo $this->inlineScript();
        echo $this->headlink()
            ->appendStylesheet($this->basePath() . '/fuelux/dist/css/fuelux.min.css')
            ->appendStylesheet($this->basePath() . '/fuelux/dist/css/fuelux-responsive.min.css');
        echo $this->headScript()
            ->prependFile($this->basePath() . '/ckeditor/ckeditor.js', 'text/javascript', array())
            ->prependFile($this->basePath() . '/fuelux/dist/loader.js', 'text/javascript', array());
        // ->prependFile($this->basePath() . '/fuelux/dist/all.js', 'text/javascript', array());
        ?>
    
    </head>
<body>
	<header>
		<div class="container">
					<div class="navbar navbar-fixed-top navbar-inverse">
					   <div class="navbar-inner">
    						<?php
                            echo $this->navigation('navigation')
                                    ->menu()
                                    ->setOnlyActiveBranch(true)
                                    ->setMinDepth(0)
                                    ->setMaxDepth(3)
                                    ->setUlClass('nav nav-tabs')
                                    ->setPartial('navigation/partials/horizontal.phtml')
                                    ->render();
                            ?>      
			            <?php if($this->auth()->loggedIn()) { ?>
		                    <ul class="nav nav-pills pull-right">
							<li class="dropdown"><a class="dropdown-toggle"
								data-toggle="dropdown" href="#"><i
									class="icon-envelope icon-white"></i><b
									class="caret caret-white"></b></a>
								<ul class="dropdown-menu">
									<li class="disabled"><a tabindex="-1" href="#">Deine
											Benachrichtigungen</a></li>
									<li class="divider"></li>
									<li><a tabindex="-1" href="#">Neuer Kommentar zu deiner Lösung</a></li>
									<li><a tabindex="-1" href="#">Deine Lösung wurde akzeptiert</a></li>
								</ul></li>
							<li class="dropdown"><a class="dropdown-toggle"
								data-toggle="dropdown" href="#"><i class="icon-cog icon-white"></i><b
									class="caret caret-white"></b></a>
								<ul class="dropdown-menu">
								</ul></li>
							<li><a href="<?php echo $this->url('logout'); ?>"><i
									class="icon-off icon-white"></i></a></li>
						</ul>
		                <?php } else { ?>
		                    <ul class="nav nav-pills pull-right">
							<li><a href="<?php echo $this->url('register'); ?>"><?php echo $this->translate('Registrieren'); ?></a>
							</li>
							<li><a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Login'); ?></a>
							</li>
						</ul>
		                <?php }?>            
                        </div>
					</div>
			</div>
	</header>

	<div class="container">
		<div class="row-fluid">
			<div class="span12" id="application">
				<div class="flasher">
                    <?php
                    if ($this->flashMessenger()->hasSuccessMessages()) {
                        echo '<div class="alert alert-success">';
                        foreach ($this->flashmessenger()->getSuccessMessages() as $message)
                            echo '<p>' . $message . '</p>';
                        echo '</div>';
                    }
                    
                    if ($this->flashMessenger()->hasErrorMessages()) {
                        echo '<div class="alert alert-error">';
                        foreach ($this->flashmessenger()->getErrorMessages() as $message)
                            echo '<p>' . $message . '</p>';
                        echo '</div>';
                    }
                    
                    if ($this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-info">';
                        foreach ($this->flashmessenger()->getMessages() as $message)
                            echo '<p>' . $message . '</p>';
                        echo '</div>';
                    }
                    ?>
        	    </div>
				<!-- <header class="page-header">
					<h1><?php echo $this->titleApplication; ?></h1>
				</header> -->
                <?php echo $this->content; ?>
            </div>
		</div>
	</div>

	<footer> </footer>
	<!-- /container -->
</body>
</html>
