<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php
        echo $this->headTitle((strlen($this->titleHead) ? $this->translate($this->titleHead) . ' - ' : '') . 'Serlo.org')
            ->setAutoEscape(false);
        ?>
        
        <?php
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
        echo $this->headScript()
            ->prependFile($this->basePath() . '/ckeditor/ckeditor.js', 'text/javascript', array(
        ));
        ?>
    
    </head>
<body>
	<header>
		<div class="container">
			<div class="row-fluid">
				<div class="span2" id="logo">
					<strong>serlo.org</strong>
				</div>
				<div class="span7">
					<nav>
						<ul id="navTop" class="nav nav-tabs">
							<li class="active"><a href="#">a234</a></li>
						</ul>
					</nav>
				</div>
				<div class="span3">
					<nav>
						<div id="navRight" class="btn-group right">
				            <?php if($this->auth()->loggedIn()) { ?>
				                <a class="btn btn-mini"
								href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Logout'); ?></a>
							<button class="btn btn-mini"><?php echo $this->translate('Einstellungen'); ?></button>
							<button class="btn btn-mini dropdown-toggle"
								data-toggle="dropdown">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li><a href="#">Benachrichtigungen</a></li>
								<li><a href="#">Benachrichtigungen</a></li>
								<li><a href="#">Benachrichtigungen</a></li>
							</ul>
			                <?php } else { ?>
								<a class="btn btn-mini btn"
								href="<?php echo $this->url('register'); ?>"><?php echo $this->translate('Registrieren'); ?></a>
							<a class="btn btn-mini btn-info"
								href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Login'); ?></a>
			                <?php }?>
		                </div>
					</nav>
				</div>
			</div>
		</div>
	</header>

	<div class="container">
		<div class="row-fluid">
			<div class="span3">
				<ul id="navSide" class="nav nav-list">
					<li class="active"><a href="#">a234</a></li>
					<li class=""><a href="#">a234</a></li>
					<li class=""><a href="#">a234</a></li>
				</ul>
				<div id="webEdu">
					<h4>Bildung im Netz</h4>
					<small>Hier steht nützliches Zeug</small>
				</div>
			</div>
			<div class="span9" id="application">
				<div class="flasher">
                    <?php
                    if ($this->flashMessenger()->hasSuccessMessages()) {
                        echo '<div class="alert alert-success">';
                        foreach ($this->flashmessenger()->getSuccessMessages() as $message)
                            echo '<p>' . $message . '</p>';
                        echo '</div>';
                    }
                    
                    if ($this->flashMessenger()->hasErrorMessages()) {
                        echo '<div class="alert alert-error">';
                        foreach ($this->flashmessenger()->getErrorMessages() as $message)
                            echo '<p>' . $message . '</p>';
                        echo '</div>';
                    }
                    
                    if ($this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-info">';
                        foreach ($this->flashmessenger()->getMessages() as $message)
                            echo '<p>' . $message . '</p>';
                        echo '</div>';
                    }
                    ?>
        	    </div>
				<!-- <header class="page-header">
					<h1><?php echo $this->titleApplication; ?></h1>
				</header> -->
                <?php echo $this->content; ?>
            </div>
		</div>
	</div>

	<footer> </footer>
	<!-- /container -->
            <?php echo $this->inlineScript()?>
    </body>
</html>
