<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="row-fluid">
	<div class="span3">
        <ul class="nav nav-list nav-stacked affix">
            <?php echo $this->activeTaxonomy; ?>
            <?php foreach($this->items as $item):?>

            <?php endforeach;?>
        </ul>
	</div>
	<div class="span9">
		<?php echo $this->content; ?>
	</div>
</div>