<?php
/* @var $entity \Entity\Entity\EntityInterface */
/* @var $options \Entity\Options\EntityOptions */
$entity = $this->entity;
$options = $this->entity()->getOptions($entity);
$url = $this->url('entity/repository/add-revision', ['entity' => $entity->getId()]);
?>

<?php if ($options->hasComponent('repository') && $this->isGranted('entity.revision.create', $entity)): ?>
    <li>
        <a href="<?php echo $url; ?>">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
    </li>
<?php endif; ?>