<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php echo $this->partial('layout/partials/head'); ?>
<body>
    <div class="wrap">
        <?php echo $this->partial('layout/partials/header'); ?>
        <div id="page" class="container col-1">
            <?php echo $this->partial('layout/partials/search'); ?>
            <section id="main">
                <div id="main-container">
                    <div id="content">
                        <?php echo $this->partial('layout/partials/notifications'); ?>
                        <div id="content-container" class="content">
                        <?php echo $this->partial('layout/partials/main'); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->partial('layout/partials/contexter'); ?>
            </section>
        </div>
        <?php echo $this->horizon(4);?>
        <?php /* sticky footer: */ ?>
        <div id="footer-push"></div>
    </div>
    <?php echo $this->partial('layout/partials/footer'); ?>
    <?php echo $this->partial('layout/partials/default-modal'); ?>
</body>
</html>
