<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php echo $this->partial('layout/partials/head'); ?>
<body>
    <div class="wrap">
        <?php echo $this->partial('layout/partials/header'); ?>

        <div id="page" class="col-1 clearfix">
            <?php echo $this->partial('layout/partials/search'); ?>
            <section class="main clearfix">
                <div id="content" class="content clearfix">
                    <?php echo $this->partial('layout/partials/notifications'); ?>
                    <?php echo $this->partial('layout/partials/main'); ?>
                </div>
                <?php echo $this->partial('layout/partials/contexter'); ?>
            </section>
            <?php echo $this->horizon(4);?>
        </div>
        <?php /* sticky footer: */ ?>
        <!-- <div id="footer-push"></div> -->
        <?php echo $this->partial('layout/partials/footer'); ?>
    </div>
    <?php echo $this->partial('layout/partials/default-modal'); ?>
</body>
</html>
