<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="en">
<head>
<meta charset="utf-8">
        <?php
        echo $this->headTitle((strlen($this->titleHead) ? $this->translate($this->titleHead) . ' - ' : '') . 'Serlo.org')
            ->setAutoEscape(false);
        
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
        echo $this->inlineScript();
        /*
         * echo $this->headlink() ->appendStylesheet($this->basePath() . '/fuelux/dist/css/fuelux.min.css') ->appendStylesheet($this->basePath() . '/fuelux/dist/css/fuelux-responsive.min.css');
         */
        echo $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js', 'text/javascript', array())
            //->prependFile($this->basePath() . '/fuelux/dist/loader.js', 'text/javascript', array());
        // ->prependFile($this->basePath() . '/fuelux/dist/all.js', 'text/javascript', array());
        ?>
    </head>
<body>
    <div class="wrap">
    	<?php echo $this->partial('layout/partials/header.phtml'); ?>

    	<div id="page" class="container">
    		<aside id="navigation">
    			<div id="navigation-container">
    				<div id="navigation-toggle" class="layout-toggle">
    					<i class="glyphicon glyphicon-list"></i>
    				</div>
                    <?php
                    echo $this->partial('layout/partials/search.phtml');

                    echo $this->navigation('navigation')
                                ->menu()
                                ->setPartial('layout/navigation/side-navigation.phtml')
                                ->setOnlyActiveBranch(true)
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav clear')
                                ->render();
                    ?>
    			</div>
    		</aside>
    		<section id="main">
    			<div id="main-container">
    				<div id="content">
    					<div id="content-container">
    						<?php echo $this->partial('layout/partials/main.phtml'); ?>
    					</div>
    				</div>
    			</div>
    		</section>
    	</div>
        <?php /* sticky footer: */ ?>
        <div id="footer-push"></div>
    </div>
    <?php echo $this->partial('layout/partials/footer.phtml'); ?>
</body>
</html>
