<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php print $this->partial('layout/partials/head'); ?>
<body>
    <div class="wrap">
    	<?php echo $this->partial('layout/partials/header.phtml'); ?>

    	<div id="page" class="container">
    		<?php echo $this->partial('layout/partials/left-sidebar'); ?>
    		<section id="main">
    			<div id="main-container">
    				<div id="content">
                        <?php echo $this->partial('layout/partials/notifications.phtml'); ?>
    					<div id="content-container">
    						<?php echo $this->partial('layout/partials/main.phtml'); ?>
    					</div>
    				</div>
    			</div>
    		</section>
            <?php echo $this->partial('layout/partials/right-sidebar'); ?>
    	</div>
        <?php /* sticky footer: */ ?>
        <div id="footer-push"></div>
    </div>
    <?php echo $this->partial('layout/partials/footer.phtml'); ?>
    <?php echo $this->partial('layout/partials/default-modal.phtml'); ?>
</body>
</html>
