<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<!--[if lt IE 9 ]>    <html class="old-ie fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <!--<![endif]-->
<?php print $this->partial('layout/partials/head'); ?>
<body>
    <header>
        <div id="serlo-menu" class="navbar navbar-default">
            <div id="editor-helpers" class="pull-left">
                <span class="helper"><?php echo $this->translate('Edit'); ?></span>
            </div>
            <div id="help-navigation" class="pull-right">
                <?php echo $this->partial('layout/partials/contexter'); ?>
            </div>
        </div>
    </header>
    <?php echo $this->partial('layout/partials/main'); ?>
    <section id="editor-wrap">
        <div id="content"></div>
        <div id="main" class="editor-main">
            <div class="editor-main-inner">

            </div>
        </div>
        <div id="preview" class="editor-main content-editor">
            <div class="editor-main-inner content">

            </div>
        </div>
        <div id="editor-actions">
            <div class="pull-right">
                <button class="btn btn-success"><?php echo $this->translate('Save'); ?></button>
                <!--<button class="btn btn-danger disabled"><?php echo $this->translate('Cancel'); ?></button>-->
            </div>
        </div>
    </section>
    <?php echo $this->partial('layout/partials/default-modal'); ?>
    <?php echo $this->tracking(); ?>
</body>
</html>