<?php
/* @var $entity \Entity\Entity\EntityInterface */
/* @var $options \Entity\Options\EntityOptions */
$entity = $this->entity;
$options = $this->entity()->getOptions($entity);
$url = $this->url('entity/repository/add-revision', ['entity' => $entity->getId()]);

if ($options->hasComponent('link')):
    /* @var $componentOptions \Entity\Options\LinkOptions */
    $componentOptions = $options->getComponent('link');
    foreach ($componentOptions->getAllowedChildren() as $type):
        $allowsManyChildren = $componentOptions->allowsManyChildren($type);
        $count              = $entity->getChildren('link')->count();
        if ($allowsManyChildren || (!$allowsManyChildren && $count < 1)):
            if ($this->isGranted('entity.link.create', $entity)):
                $url = $this->url(
                    'entity/create',
                    ['type' => $type],
                    ['query' => ['link' => ['type' => 'link', 'child' => $entity->getId()]]]
                ); ?>
                <li>
                    <a href="<?php echo $url; ?>"> <span class="glyphicon glyphicon-plus"></span>
                        <?php echo sprintf($this->translate('Add %s'), $type); ?>
                    </a>
                <li>
            <?php endif;
        endif;
    endforeach;
endif; ?>