<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Julian Kempff (julian.kempff@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
foreach ($this->pages as $page) {
    $liClasses = [];
    // visibility of the sub-page
    if (! $page->isVisible()) {
        continue;
    }
    if ($page->getLabel() == 'divider') {
        $html[] = '<li class="divider"></li>';
        continue;
    }

    $dropdown = ! empty($page->pages);

    if ($dropdown) {
        $liClasses[] = 'dropdown-submenu';
    }

    if ($page->isActive()) {
        $liClasses[] = 'active';
    }

    $html[] = '<li' . (count($liClasses) ? (' class="' . implode(' ', $liClasses) . '"">') : '>');

    if ($dropdown) {
        $html[] = '<a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="' . $page->getHref() . '">';
    } else {
        $html[] = '<a href="' . $page->getHref() . '">';
    }

    if ($page->get('icon')) {
        $html[] = '<i class="icon-' . $page->get('icon') . '"></i>';
    }

    $html[] = $page->getLabel();
    $html[] = "</a>";

    if ($dropdown) {
        $html[] = '<ul class="dropdown-menu">';
        $html[] = $this->partial('layout/navigation/partial/nested-navigation-list', array('pages' => $page->pages));
        $html[] = '</ul>';
    }

    $html[] = "</li>";
}

echo join(PHP_EOL, $html);