<?php echo $this->pageHeader('Manage context links')->render(); ?>
<table class="table">
	<thead>
		<tr>
			<th><?php echo $this->translate('Link'); ?></th>
			<th><?php echo $this->translate('Matching'); ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	    <?php /* @var $element \Contexter\ContextInterface */ ?>
	    <?php foreach($this->elements as $element):?>
		<tr>
			<td><a href="<?php echo $element->getUrl(); ?>"><?php echo $element->getTitle(); ?></a>
			</td>
			<td>
    		     <?php foreach($element->getRoutes() as $route): ?>
    		          <div class="btn-group">
                        <div class="btn-group">
                            <div class="btn btn-xs btn-default" role="button" data-toggle="dropdown" data-target="#">
    			                 <?php echo $route->getName(); ?> <span class="caret"></span>
                            </div>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                			     <?php foreach($route->getParameters() as $parameter): ?>
                			         <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><b><?php echo $parameter->getKey(); ?>:</b> <?php echo $parameter->getValue();?></a></li>
                		         <?php endforeach; ?>
                            </ul>
                        </div>
			            <a class="btn btn-default btn-xs" href="<?php echo $this->url('contexter/route/remove', array('id' => $route->getId())); ?>"><span class="glyphicon glyphicon-trash"></span></a>
    			        <!-- <a class="btn btn-success btn-xs"><span class="glyphicon glyphicon-plus"></span></a> -->
    		         </div>
    	         <?php endforeach; ?>
			</td>
			<td>
			     <div class="btn-group">
    			     <a class="btn btn-danger btn-xs" href="<?php echo $this->url('contexter/remove', array('id' => $element->getId())); ?>"><span class="glyphicon glyphicon-remove"></span></a>
			     </div>
			</td>
		</tr>
        <?php endforeach; ?>
	</tbody>
</table>