
<?php if($this->container->getResults()->count()): ?>
    <div class="group-list">
        <?php if($this->container->getName()): ?>
            <div class="list-group-item"
                <h4 class="list-group-item-heading"><?php echo $this->translate($this->container->getName()); ?></h4>
            </div>
        <?php endif; ?>
        <?php /* @var $result \Search\Result\ResultInterface */?>
        <?php foreach($this->container->getResults() as $result): ?>
            <a class="list-group-item" href="<?php echo $this->normalize()->toUrl($result->getObject()); ?>">
                <?php echo $this->normalize()->toTitle($result->getObject()); ?>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php foreach($this->container->getContainers() as $container): ?>
    <?php echo $this->partial('search/container', array('container' => $container)); ?>
<?php endforeach; ?>