<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="right btn-group">
	<a
		href="<?php echo $this->url('taxonomy/term',array('action' => 'set-topic', 'id' => $this->entity->getId() )) . '?term='.$this->term->getId(); ?>"
		class="btn btn-mini<?php echo ($this->term->getId() == $this->entity->getTopic()->getId()) ? ' disabled' : ' '; ?>"><i class="icon-download-alt"></i></a>
</div>