<?php /* @var $related \RelatedContent\Result\ResultInterface */ ?>
<strong><?php echo $this->translate('Related content'); ?></strong>
<ul>
    <?php foreach ($this->aggregated as $related): ?>
        <?php if ($related->getType() == 'category'): ?>
        </ul>
        <ul>
            <li><h5><?php echo $related->getTitle(); ?></h5>
        <?php elseif ($related->getType() == 'internal'): ?>
            <li>
            <a href="<?php echo $related->getUrl(); ?>"><?php echo $related->getTitle(); ?></a>
        <?php elseif ($related->getType() == 'external'): ?>
            <li>
            <a href="<?php echo $related->getUrl(); ?>"><?php echo $related->getTitle(); ?></a>
        <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>