<?php /* @var $flag \Flag\Service\FlagServiceInterface */ ?>
<?php $flag = $this->flag; ?>
<?php $left = 'col-md-4'; ?>
<?php $right = 'col-md-8'; ?>
<?php echo $this->pageHeader('Flag detail', $flag->getId())->render(); ?>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Id'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <?php echo $flag->getId(); ?>
    </div>
</div>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Object'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <a href="<?php echo $this->url('uuid/router',array('uuid' => $flag->getObject()->getId())); ?>"><?php echo $flag->getObject()->getUuid(); ?></a>
    </div>
</div>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Type'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <?php echo $flag->getType()->getName(); ?>
    </div>
</div>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Timestamp'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <?php echo $this->timeago()->render($flag->getTimestamp()); ?>
    </div>
</div>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Reporter'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <a href="<?php echo $this->url('uuid/router', array('uuid' => $flag->getReporter()->getId())); ?>"><?php echo $flag->getReporter()->getUsername(); ?></a>
    </div>
</div>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Content'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <?php echo $flag->getContent(); ?>
    </div>
</div>