<?php
/* @var $entity \Entity\Entity\EntityInterface */
/* @var $options \Entity\Options\EntityOptions */
$entity = $this->entity;
$options = $this->entity()->getOptions($entity);

if ($this->isGranted('related_content.manage', $entity)): ?>
    <li>
        <a href="<?php echo $this->url('related-content/manage', array('id' => $entity->getId())); ?>"> <span
                class="glyphicon glyphicon-link"></span>
            <?php echo $this->translate('Manage related items'); ?>
        </a>
    </li>
<?php endif; ?>