<div class="container">
<div class="row">
	<div class="col-md-3 col-sm-4 col-xs-4 col-lg-2">
		<small> <a href="">
        <?php echo $this->translate('Horizon'); ?>
        <span class="glyphicon glyphicon-info-sign"></span>
		</a>
		</small>
	</div>
	
</div>
</div>
<div class="container">
	<div class="row-fluid">

		<?php  foreach ($this->ads as $ad) :?>
		    <div class="col-md-3 col-sm-4 col-xs-6 ">
		  
			<a
				href="<?php echo $this->url('ads/ad/out',array('id'=>$ad->getId()));?>" target="__blank">
				<button type="button" class="btn btn-default">
				
                    <?php echo $ad->getTitle();?>	
                    <hr> <img alt="<?php echo $ad->getTitle();?>"
						src="<?php echo $ad->getImage()->getLocation();?>"
						class="img-responsive" /> <small>
        	           <?php echo $ad->getContent();?>
                    </small>
				
				</button></a>
			
		
		</div>
        <?php endforeach; ?>
        </div>
</div>