<div id="horizon">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-default btn-xs pull-right" href="<?php echo $this->url('ads/about');?>"><?php echo $this->translate('Horizon'); ?><i class="glyphicon glyphicon-info-sign"></i></a>
        </div>
    </div>
    <div class="row">
    	<?php  if ($this->ads!=null):foreach ($this->ads as $count => $ad) : ?>
    	    <div class="col-md-4 col-sm-4 col-xs-6<?php if ($count > 1) : ?> hidden-xs<?php endif; ?>">
                <a class="ad" href="<?php echo $this->url('ads/ad/out',array('id'=>$ad->getId()));?>" target="_blank">
                    <img alt="<?php echo $ad->getTitle();?>" src="<?php echo $ad->getImage()->getLocation();?>" class="img-responsive" />
                    <div class="caption">
                        <h4><?php echo $ad->getTitle();?></h4>
                        <?php echo $ad->getContent(); ?>
                    </div>
    			</a>
    	   </div>
        <?php endforeach;endif; ?>
    </div>
</div>