<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="entities">
    <?php foreach($this->entities as $entity): ?>
        <?php if($this->plugin->isTypeEnabled($entity->getType()->getName())): ?>
            <?php $content = $this->partial($this->plugin->getTemplateForEntityType($entity->getType()->getName()), array('entity' => $entity)); ?>
            <?php if($content): ?>
                <div class="entity">
                    <div class="right btn-group">
                    	<a
                    		href="<?php echo $this->url('subject/plugin/curriculum/entity', 
                		      array('action' => 'remove',
                                    'curriculum' => $this->curriculum->getId(),
                                    'subject' => $this->subject->getSlug(),
                		            'entity' => $entity->getId())); ?>"
                    		class="btn btn-mini"><i class="icon-trash"></i></a>
                    </div>
                </div>
                <?php echo $content; ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>