<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
if(!isset($this->defaultDepth))
    $this->defaultDepth = 2;

$selected = NULL;
if(is_object($this->selectedCurriculum)){
    $onLevel =  ($this->defaultDepth - $this->renderChildren);
    $selected = $this->selectedCurriculum;
    for($i = 1; $i <= $onLevel; $i++){
        $selected = $selected->getParent();
    }
}
?>
<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <?php foreach($this->terms as $term): ?>
        <li class="<?php if($selected === $term) echo 'disabled ';?><?php if($this->renderChildren > 0 && $term->hasChildren()) echo 'dropdown-submenu ';?>">
            <a tabindex="-1" href="<?php echo ($term->getTaxonomy()->getName() != 'curriculum') ? '#' : $this->url('subject/plugin/curriculum/topic', array('subject' => $this->subject->getSlug(), 'curriculum' => $term->getId(), 'path' => ''));?>"><?php echo $term->getName(); ?></a>
            <?php if($this->renderChildren > 0 && $term->hasChildren()): ?>
                <?php echo $this->partial('subject/plugin/curriculum/school-type', array('terms' => $term->getChildren(), 'renderChildren' => $this->renderChildren--, 'subject' => $this->subject)); ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>