<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
//$subtitle = is_object($this->topic) ? $this->topic->getName() : NULL;
echo $this->pageHeader($this->translate('Lehrplan'));
?>
<div class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate('Wähle einen Lehrplan');?></a>
    <?php echo $this->partial('subject/plugin/curriculum/school-type', array('terms' => $this->schoolRootFolders, 'renderChildren' => 2, 'currentCurriculum' => $this->curriculum, 'subject' => $this->subject)); ?>
</div>
<?php echo $this->topics; ?>
<?php echo $this->entities; ?>