<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<ul>
    <?php foreach($this->plugin->filterTopicChildren($this->terms) as $term): ?>
    <li class="term" data-id="<?php echo $term->getId(); ?>">
    	<div class="" style="margin: 5px 0;">
    		<div>
    			<a class=""
    				href="<?php echo rawurldecode($this->url('subject/plugin/curriculum/topic', array('curriculum' => $curriculum->getId(), 'subject' => $this->subject->getSlug(), 'path' => $this->plugin->getTopicPath($term)))); ?>"><?php echo $term->getName(); ?></a>
    			(<?php echo $term->countLinks('entities'); ?>)
    		</div>
    	</div>
        <?php echo $this->partial('subject/plugin/curriculum/topic', array('terms' => $term->getChildren(), 'subject' => $this->subject, 'plugin' => $this->plugin, 'curriculum' => $this->curriculum)); ?>
    </li>
    <?php endforeach; ?>
</ul>