<?php
/* @var $module \Entity\Entity\EntityInterface */
$module = $this->entity;
if($module->hasCurrentRevision()): ?>
    <?php $revision = $module->getCurrentRevision(); ?>
    <li class="list-group-item">
        <a href="<?php echo $this->url('entity/page', array('entity' => $module->getId())); ?>" class="module">
        	<?php echo $revision->get('title'); ?>
        </a>
    </li>
<?php endif; ?>