<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<li class="<?php if($this->item['active']) echo 'active'; ?>"><a href="<?php echo $this->item['href']; ?>"><?php echo $this->item['content']; ?></a>
	<?php if($this->item['children']): ?>
	<?php foreach($this->item['children'] as $child): ?>
	<?php echo $this->partial('navigation/sidenav/partial',array('item' => $child));?>
	<?php endforeach; endif; ?>
</li>