<?php /* @var $container \Navigation\Entity\ContainerInterface */ ?>
<?php $container = $this->container; ?>
<?php echo $this->pageHeader('Manage navigation')->setSubtitle($container->getType()->getName())->render(); ?>
<h3><?php echo $this->translate('Information'); ?></h3>
<ul>
    <li>
        <?php echo $this->translate('Instance: ') . $container->getInstance(); ?>
    </li>
    <li>
        <?php echo $this->translate('Name: ') . $container->getType(); ?>
    </li>
</ul>
<a class="pull-right btn btn-xs btn-default"
   href="<?php echo $this->url('navigation/page/create', ['container' => $container->getId()]); ?>">
    <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('page'); ?>
</a>
<h3><?php echo $this->translate('Pages'); ?></h3>
<?php echo $this->partial('navigation/page/partial/tree', ['pages' => $container->getPages(), 'positionForm' => $this->positionForm]); ?>