<?php echo $this->pageHeader('Unrevised learning resources')->setSubtitle($this->subject->getName())->append($this->contexter()->renderButton())->render(); ?>
<table class="table table-striped">
	<thead>
		<tr>
			<th><?php echo $this->translate('Title'); ?></th>
			<th><?php echo $this->translate('Type'); ?></th>
		</tr>
	</thead>
	<tbody>
        <?php foreach($this->entities as $entity): ?>
        <tr>
			<td><a href="<?php echo $this->url('entity/repository/history', array('entity' => $entity->getId())); ?>"><?php echo $this->normalize()->toTitle($entity); ?></a></td>
			<td><?php echo $entity->getType()->getName(); ?></td>
		</tr>
        <?php endforeach; ?>
	</tbody>
</table>