<?php echo $this->pageHeader('Manage licenses')->render(); ?>
<table class="table">
	<thead>
		<tr>
			<th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Default'); ?></th>
			<th><?php echo $this->translate('Url'); ?></th>
			<th><?php echo $this->translate('Icon'); ?></th>
			<th><?php echo $this->translate('Actions'); ?></th>
		</tr>
	</thead>
	<tbody>
        <?php /* @var $license \License\Entity\LicenseInterface */ ?>
        <?php foreach($this->licenses as $license): ?>
            <tr>
                <td><?php echo $license->getTitle(); ?></td>
                <td><?php echo $license->isDefault() ? '<span class="glyphicon glyphicon-ok"></span>' : ''; ?></td>
                <td><a href="<?php echo $license->getUrl(); ?>"><?php echo $license->getUrl(); ?></a></td>
                <td><img height="30" src="<?php echo $license->getIconHref(); ?>" /></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-default" href="<?php echo $this->url('license/detail', array('id' => $license->getId())); ?>"><span class="glyphicon glyphicon-search"></span></a>
                        <a class="btn btn-sm btn-default" href="<?php echo $this->url('license/update', array('id' => $license->getId())); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                        <button class="btn btn-sm btn-danger dialog" href="<?php echo $this->url('license/remove', array('id' => $license->getId())); ?>" data-content="<?php echo $this->translate('Caution, deleting a license has serious consequences. You are going to delete a great amount of content, you need to know exactly what you are doing! THIS ACTION CAN NOT BE UNDONE'); ?>" data-title="<?php echo $this->translate('DANGER: You are going to delete all contents associated with this license!'); ?>" data-type="danger"><span class="glyphicon glyphicon-trash"></span></button>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
	</tbody>
</table>
<div class="clearfix">
    <a class="pull-right btn btn-sm btn-success" href="<?php echo $this->url('license/add'); ?>"><span class="glyphicon glyphicon-file"></span></a>
</div>