<?php foreach($this->term->getChildren() as $term): ?>    	
    <h4>
        <a class="" href="<?php echo rawurldecode($this->url($this->plugin->getRoute(), array('subject' => $this->subject->getSlug(), 'path' => $this->plugin->getPathToTermAsUri($term)))); ?>">
            <?php echo $term->getName(); ?>
        </a>
    </h4>	    
    <ol>
        <?php if($term->isAssociationAllowed('entities')): ?>
            <?php foreach($term->getAssociated('entities') as $entity): ?>
                <?php if($this->plugin->isTypeEnabled($entity->getType()->getName() && !$entity->getTrashed())): ?>
                    <?php echo $this->partial('subject/plugin/taxonomy/entity/default', array('entity' => $entity)); ?>
                <?php endif; ?>
            <?php endforeach;?>
        <?php endif;?>
    </ol>
<hr>
<?php endforeach; ?>