<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$table = array(
    'left' => '',
    'middle' => '',
    'right' => '',
    'bottom' => ''
);
?>
<?php if(is_object($this->term)): ?>
    <div class="row">
    	<div class="col-md-9">
            <?php if($this->term->getDescription()): ?>
                <p class="lead"><?php echo $this->term->getDescription(); ?></p>
            <?php else: ?>
                <p class="text-muted"><?php echo $this->translate('No description set.'); ?></p>
            <?php endif;?>
    	</div>
    	<div class="col-md-3">
    		<div class="btn-group pull-right">
    		    <?php if($this->guard()->hasAccessToRoute('entity/create')): ?>
                    <div class="btn-group">
            			<a class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" href="#">
            			     <span class="glyphicon glyphicon-file"></span> <span class="caret"></span>
            			</a>
            			<ul class="dropdown-menu">
                            <?php foreach($this->plugin->getEnabledEntityTypes() as $type):?>
            				    <li>
            				        <a href="<?php echo $this->url('entity/create', array('type' => $type), array('query' => array( 'taxonomy' => array( 'term' => $this->term->getId())))); ?>">
            					       <?php echo $this->plugin->getEntityTypeLabel($type, 'singular');?>
        					       </a>
        					   </li>
            				<?php endforeach; ?>
            			</ul>
        			</div>
    			<?php endif; ?>
    		    <?php if($this->guard()->hasAccessToRoute('taxonomy/term/sort-associated')): ?>
        			<a class="btn btn-default btn-xs" href="<?php echo $this->url('taxonomy/term/sort-associated', array('association' => 'entities', 'term' => $this->term->getId())); ?>">
        			     <span class="glyphicon glyphicon-sort"></span>
        			</a>
    			<?php endif; ?>
    		</div>
    	</div>
    </div>
    <hr />
    <div class="entities">
        <?php foreach($this->links as $link): ?>
            <?php $partial = $this->partial('subject/plugin/taxonomy/entity/default', array('entity' => $link)); ?>
            <?php switch($link->getType()->getName()){ 
                case 'article': $table['left'] .= $partial; break; ?>
                <?php case 'text-exercise': $table['bottom'] .= $partial; break; ?>
                <?php case 'exercise-group': $table['bottom'] .= $partial; break; ?>
                <?php case 'video': $table['middle'] .= $partial; break; ?>
                <?php case 'module': $table['right'] .= $partial; break; ?>
                <?php default: $table['left'] .= $partial; break;?>
            <?php } ?>
        <?php endforeach; ?>
        <div class="row">
    		<div class="col-md-4">
    			<ol class="list-group">
                    <li class="list-group-item">
    			         <h4><span class="glyphicon glyphicon-book"></span> <strong><?php echo $this->translate('Articles'); ?></strong></h4>
    			    </li>
    			    <?php if(strlen($table['left']) > 0): ?>
                        <?php echo $table['left']; ?>
                    <?php else: ?>
                        <li class="list-group-item">
                        	<span class="text-muted"><?php echo $this->translate('There are no articles for this topic yet.'); ?></span>
                        </li>
                    <?php endif; ?>
                </ol>
    		</div>
    		<div class="col-md-4">
    			<ol class="list-group">
                    <li class="list-group-item">
    			         <h4><span class="glyphicon glyphicon-facetime-video"></span> <strong><?php echo $this->translate('Videos'); ?></strong></h4>
    			    </li>
    			    <?php if(strlen($table['middle']) > 0): ?>
                        <?php echo $table['middle']; ?>
                    <?php else: ?>
                        <li class="list-group-item">
                        	<span class="text-muted"><?php echo $this->translate('There are no videos for this topic yet.'); ?></span>
                        </li>
                    <?php endif; ?>
                </ol>
            </div>
    		<div class="col-md-4">
    			<ol class="list-group">
                    <li class="list-group-item">
    			         <h4><span class="glyphicon glyphicon-list"></span> <strong><?php echo $this->translate('Modules'); ?></strong></h4>
    			    </li>
    			    <?php if(strlen($table['right']) > 0): ?>
                        <?php echo $table['right']; ?>
                    <?php else: ?>
                        <li class="list-group-item">
                        	<span class="text-muted"><?php echo $this->translate('There are no modules for this topic yet.'); ?></span>
                        </li>
                    <?php endif; ?>
                </ol>
            </div>
    	</div>
    	<hr>
    	<div class="row">
    		<div class="col-md-12">
    		    <h4><span class="glyphicon glyphicon-edit"></span> <strong><?php echo $this->translate('Exercises'); ?></strong></h4>
    		    <div class="list-group">
        		    <?php if(strlen($table['bottom']) > 0): ?>
                        <?php echo $table['bottom']; ?>
                    <?php else: ?>
                    	<div class="list-group-item">
                    	   <p class="text-muted"><?php echo $this->translate('There are no exercises for this topic yet.'); ?></p>
                    	</div>
                    <?php endif; ?>
                </div>
            </div>
    	</div>
    </div>
<?php endif; ?>