<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$table = array(
    'left' => '',
    'middle' => '',
    'right' => '',
    'bottom' => ''
);
?>
<?php if(is_object($this->term)): ?>
    <div class="row">
    	<div class="col-md-9"></div>
    	<div class="col-md-3">
    	    <?php if($this->term->isAssociationAllowed('entities')): ?>
    		<div class="btn-group pull-right">
    			<a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"> <i
    				class="icon-plus"></i><?php echo $this->translate('hinzufügen');?> <span
    				class="caret"></span>
    			</a>
    			<ul class="dropdown-menu">
                    <?php foreach($this->plugin->getEnabledEntityTypes() as $type):?>
    				    <li><a
    					href="<?php echo rawurldecode($this->url('entity/create', array('type' => $type), array('query' => array( 'taxonomy' => array( 'term' => $this->term->getId()))))); ?>"><?php echo $this->plugin->getEntityTypeLabel($type, 'singular');?></a></li>
    				<?php endforeach; ?>
    			</ul>
    		</div>
    		<?php endif; ?>
    	</div>
    </div>
    <?php if($this->term->isAssociationAllowed('entities')): ?>
    <div class="entities">
        <?php foreach($this->links as $link): ?>
            <?php if($this->plugin->isTypeEnabled($link->getType()->getName())): ?>
                <?php $partial = $this->partial($this->plugin->getTemplateForEntityType($link->getType()->getName()), array('entity' => $link)); ?>
                <?php switch($link->getType()->getName()){ 
                    case 'article': $table['left'] .= $partial; break; ?>
                    <?php case 'text-exercise': $table['bottom'] .= $partial; break; ?>
                    <?php case 'exercise-group': $table['bottom'] .= $partial; break; ?>
                    <?php case 'video': $table['middle'] .= $partial; break; ?>
                    <?php case 'module': $table['right'] .= $partial; break; ?>
                    <?php default: $table['left'] .= $partial; break;?>
                <?php } ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <div class="row">
    		<div class="col-md-4">
    		    <div class="sortable" data-action="/save/my/sort" data-depth="1">
        			<ol class="sortable-list">
                        <li>
        			         <h4><span class="glyphicon glyphicon-book"></span> <strong><?php echo $this->translate('Articles'); ?></strong></h4>
        			    </li>
        			    <?php if(strlen($table['left']) > 0): ?>
                            <?php echo $table['left']; ?>
                        <?php else: ?>
                            <li>
                            	<span class="text-muted"><?php echo $this->translate('There are no articles for this topic yet.'); ?></span>
                            </li>
                        <?php endif; ?>
                    </ol>
                    <div class="sortable-actions">
                        <button class="btn btn-success sortable-save-action is-hidden">
                            <?php echo $this->translate('Save'); ?>
                        </button>
                    </div>
                </div>
    		</div>
    		<div class="col-md-4">
    		    <div class="sortable" data-action="/save/my/sort" data-depth="1">
        			<ol class="sortable-list">
                        <li>
        			         <h4><span class="glyphicon glyphicon-facetime-video"></span> <strong><?php echo $this->translate('Videos'); ?></strong></h4>
        			    </li>
        			    <?php if(strlen($table['middle']) > 0): ?>
                            <?php echo $table['middle']; ?>
                        <?php else: ?>
                            <li>
                            	<span class="text-muted"><?php echo $this->translate('There are no videos for this topic yet.'); ?></span>
                            </li>
                        <?php endif; ?>
                    </ol>
                    <div class="sortable-actions">
                        <button class="btn btn-success sortable-save-action is-hidden">
                            <?php echo $this->translate('Save'); ?>
                        </button>
                    </div>
                </div>
            </div>
    		<div class="col-md-4">
    		    <div class="sortable" data-action="/save/my/sort" data-depth="1">
        			<ol class="sortable-list">
                        <li>
        			         <h4><span class="glyphicon glyphicon-list"></span> <strong><?php echo $this->translate('Modules'); ?></strong></h4>
        			    </li>
        			    <?php if(strlen($table['right']) > 0): ?>
                            <?php echo $table['right']; ?>
                        <?php else: ?>
                            <li>
                            	<span class="text-muted"><?php echo $this->translate('There are no modules for this topic yet.'); ?></span>
                            </li>
                        <?php endif; ?>
                    </ol>
                    <div class="sortable-actions">
                        <button class="btn btn-success sortable-save-action is-hidden">
                            <?php echo $this->translate('Save'); ?>
                        </button>
                    </div>
                </div>
            </div>
    	</div>
    	<hr>
    	<div class="row">
    		<div class="col-md-12">
    		    <h4><span class="glyphicon glyphicon-edit"></span> <strong><?php echo $this->translate('Exercises'); ?></strong></h4>
    		    <div class="sortable" data-action="<?php echo $this->url('taxonomy/term/sort-associated', array('association' => 'entities', 'term' => $this->term->getId())); ?>" data-depth="1">
        		    <ol class="sortable-list">
            		    <?php if(strlen($table['bottom']) > 0): ?>
                            <?php echo $table['bottom']; ?>
                        <?php else: ?>
                        	<li>
                        	   <p class="text-muted"><?php echo $this->translate('There are no exercises for this topic yet.'); ?></p>
                        	</li>
                        <?php endif; ?>
                    </ol>
                    <div class="sortable-actions">
                        <button class="btn btn-success sortable-save-action is-hidden">
                            <?php echo $this->translate('Save'); ?>
                        </button>
                    </div>
                </div>
            </div>
    	</div>
    </div>
    <?php endif; ?>
<?php endif; ?>