<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$table = array(
    'left' => '',
    'middle' => '',
    'right' => '',
    'bottom' => ''
);
?>
<div class="row">
	<div class="col-md-9"></div>
	<div class="col-md-3">
	    <?php if($this->acceptsEntities): ?>
		<div class="btn-group pull-right">
			<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"> <i
				class="icon-plus"></i><?php echo $this->translate('hinzufügen');?> <span
				class="caret"></span>
			</a>
			<ul class="dropdown-menu">
                <?php foreach($this->plugin->getEnabledEntityTypes() as $type):?>
				    <li><a
					href="<?php echo rawurldecode($this->url('entity/create', array('type' => $type), array('query' => array( 'taxonomy' => array( 'term' => $this->term->getId()))))); ?>"><?php echo $this->plugin->getEntityTypeLabel($type, 'singular');?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
		<?php endif; ?>
	</div>
</div>
<?php if($this->acceptsEntities): ?>
<div class="entities">
    <?php foreach($this->links as $link): ?>
    <?php if($this->plugin->isTypeEnabled($link->getType()->getName())): ?>
    <?php $partial = $this->partial($this->plugin->getTemplateForEntityType($link->getType()->getName()), array('entity' => $link)); ?>
    <?php switch($link->getType()->getName()){ 
        case 'article': $table['left'] .= $partial; break; ?>
        <?php case 'text-exercise': $table['bottom'] .= $partial; break; ?>
        <?php case 'video': $table['middle'] .= $partial; break; ?>
        <?php case 'module': $table['right'] .= $partial; break; ?>
        <?php default: $table['left'] .= $partial; break;?>
    <?php } ?>
    <?php endif; ?>
    <?php endforeach; ?>
    <div class="row">
		<div class="col-md-4">
			<div class="list-group">
                <div>
			         <h4><span class="glyphicon glyphicon-book"></span> <strong><?php echo $this->translate('Artikel'); ?></strong></h4>
			    </div>
                <?php echo $table['left']; ?>
            </div>
		</div>
		<div class="col-md-4">
			<ul class="nav nav-pills nav-stacked">
                <li class="disabled">
			         <h4><span class="glyphicon glyphicon-facetime-video"></span> <strong><?php echo $this->translate('Videos'); ?></strong></h4>
			    </li>
                <?php echo $table['middle']; ?>
            </ul>
        </div>
		<div class="col-md-4">
			<ul class="nav nav-pills nav-stacked">
                <li class="disabled">
			         <h4><span class="glyphicon glyphicon-list"></span> <strong><?php echo $this->translate('Module'); ?></strong></h4>
			    </li>
                <?php echo $table['right']; ?>
            </ul>
        </div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
		    <h4><span class="glyphicon glyphicon-edit"></span> <strong><?php echo $this->translate('Aufgaben'); ?></strong></h4>
		    <ol>
		    </ol>
            <?php echo $table['bottom']; ?>
        </div>
	</div>
</div>
<?php endif; ?>