<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="row-fluid">
	<div class="span9"></div>
	<div class="span3">
	    <?php if($this->acceptsEntities): ?>
		<div class="btn-group pull-right">
			<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"> <i
				class="icon-plus"></i><?php echo $this->translate('hinzufügen');?> <span
				class="caret"></span>
			</a>
			<ul class="dropdown-menu">
                <?php foreach($this->plugin->getEnabledEntityTypes() as $type):?>
				    <li><a
					href="<?php echo rawurldecode($this->url('entity/create', array('type' => $type), array('query' => array( 'taxonomy' => array( 'term' => $this->term->getId()))))); ?>"><?php echo $this->plugin->getEntityTypeLabel($type, 'singular');?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
		<?php endif; ?>
	</div>
</div>
<?php if($this->acceptsEntities): ?>
<div class="entities">
    <?php foreach($this->links as $link): ?>
    <?php if($this->plugin->isTypeEnabled($link->getType()->getName())): ?>
    <div class="right btn-group">
		<a
			href="<?php echo $this->url('entity/plugin/topic-folder', array('action' => 'set', 'entity' => $link->getId() )); ?>"
			class="btn btn-mini"><i class="icon-download-alt"></i></a>
	</div>
    <?php echo $this->partial($this->plugin->getTemplateForEntityType($link->getType()->getName()), array('entity' => $link)); ?>
    <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>