<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<ul class="nav nav-side">
    <?php foreach($this->terms as $term): ?>
    <li <?php echo (isset($this->recursion) && $this->recursion) ? 'class="nav-side-header"' : ''; ?>>
    
    <?php if (isset($this->recursion) && $this->recursion): ?>
    <a
		href="<?php echo rawurldecode($this->url($this->plugin->getRoute(), array('subject' => $this->subject->getSlug(), 'path' => $this->plugin->getPathToTermAsUri($term)))); ?>"><?php echo $term->getName(); ?></a>
		<?php else: ?>
		<strong><?php echo $term->getName(); ?></strong>
		<?php endif;?>
        <?php echo $this->partial($this->plugin->getTemplate('taxonomy'), array('terms' => $term->getChildren(), 'subject' => $this->subject, 'plugin' => $this->plugin, 'recursion' => true)); ?>
    </li>
    <?php endforeach; ?>
</ul>