<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */

$columns = 3;
$columnsClass = 'col-xs-' . (12 / $columns);

?>
<?php if (empty($this->recursion)) : ?>
<ul class="nav nav-side row">
    <?php foreach ($this->terms as $key => $term) : ?>
        <?php if(!$term->isTrashed()): ?>
            <?php if ($key !== 0 && $key % $columns === 0) : ?>
            </ul><ul class="nav nav-side row">
            <?php endif; ?>
            <li class="<?php echo $columnsClass; ?>">
                <a href="<?php echo $this->url($this->plugin->getRoute(), array('subject' => $this->subject->getSlug(), 'path' => $this->plugin->getPathToTermAsUri($term))); ?>">
                    <strong><?php echo $term->getName(); ?></strong>
                </a>
                <?php echo $this->partial($this->plugin->getTemplate('taxonomy'), array('terms' => $term->getChildren(), 'subject' => $this->subject, 'plugin' => $this->plugin, 'recursion' => true)); ?>
            </li>
            <?php //$liCount++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php else : ?>
<ul class="nav nav-side">
    <?php foreach ($this->terms as $term) : ?>
        <?php if(!$term->isTrashed()): ?>
            <li>
                <a href="<?php echo $this->url($this->plugin->getRoute(), array('subject' => $this->subject->getSlug(), 'path' => $this->plugin->getPathToTermAsUri($term))); ?>">
                    <?php echo $term->getName(); ?>
                </a>
                <?php echo $this->partial($this->plugin->getTemplate('taxonomy'), array('terms' => $term->getChildren(), 'subject' => $this->subject, 'plugin' => $this->plugin, 'recursion' => true)); ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>