<div class="tab-content">
    <?php if ($this->isArchived === NULL): ?>
        <h3><?php echo $this->translate('Discussions'); ?></h3>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#current" data-toggle="tab"><?php echo $this->translate('Current'); ?></a></li>
            <li><a href="#archived" data-toggle="tab"><?php echo $this->translate('Archived'); ?></a></li>
        </ul>
        <div class="tab-pane active" id="current">
            <div class="alert alert-info"><?php echo $this->translate(
                    'See what others have to say or participate in the process and start discussing!'
                ); ?></div>
            <?php echo $this->discussion($this->object, $this->forum, false)->render(); ?>
        </div>
        <div class="tab-pane" id="archived">
            <div class="alert alert-info"><?php echo $this->translate(
                    'See what topics have been discussed and what results have been achieved!'
                ); ?></div>
            <?php echo $this->discussion($this->object, $this->forum, true)->render(); ?>
        </div>
    <?php else: ?>
        <div class="list-group">
            <?php if ($this->isGranted('discussion.create')): ?>
                <?php $form = $this->discussion()->getForm('discussion'); ?>
                <?php $form->setAttribute(
                    'action',
                    $this->url(
                        'discussion/discussion/start',
                        ['on' => $this->object->getId(), 'forum' => $this->forum->getId()]
                    )
                ); ?>
                <?php if (!$this->isArchived): ?>
                    <div class="list-group-item">
                        <h4><?php echo $this->translate('Start a new discussion'); ?></h4>
                        <hr>
                        <?php echo $this->form()->render($form, null); ?>
                    </div>
                <?php endif; ?>
                <?php foreach ($this->discussions as $discussion): ?>
                    <div class="list-group-item">
                        <?php echo $this->partial(
                            'discussion/discussion/show',
                            array('discussion' => $discussion)
                        ); ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>