<div class="tab-content">
    <h3><?php echo $this->translate('Discussions'); ?></h3>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#current" data-toggle="tab"><?php echo $this->translate('Current'); ?></a></li>
        <li><a href="#archived" data-toggle="tab"><?php echo $this->translate('Archived'); ?></a></li>
    </ul>
    <div class="tab-pane active" id="current">
        <div class="list-group">
            <?php if ($this->isGranted('discussion.create')): ?>
                <?php $form = $this->discussion()->getForm('discussion'); ?>
                <?php $form->setAttribute(
                    'action',
                    $this->url(
                        'discussion/discussion/start',
                        ['on' => $this->object->getId(), 'forum' => $this->forum->getId()]
                    )
                ); ?>
                    <div class="list-group-item">
                        <h4><?php echo $this->translate('Start a new discussion'); ?></h4>
                        <hr>
                        <?php echo $this->form()->render($form, null); ?>
                    </div>
            <?php endif; ?>
            <?php $discussions = $this->discussion()->getDiscussions($this->object); ?>
            <?php if (!count($discussions)): ?>
                <div class="alert alert-info"><?php echo $this->translate(
                        'There are no discussions on this topic yet.'
                    ); ?></div>
            <?php endif; ?>
            <?php foreach ($discussions as $discussion): ?>
                <div class="list-group-item">
                    <?php echo $this->partial(
                        'discussion/discussion/show',
                        array('discussion' => $discussion)
                    ); ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="tab-pane" id="archived">
        <div class="list-group">
            <?php if ($this->isGranted('discussion.create')): ?>
                <?php $form = $this->discussion()->getForm('discussion'); ?>
                <?php $form->setAttribute(
                    'action',
                    $this->url(
                        'discussion/discussion/start',
                        ['on' => $this->object->getId(), 'forum' => $this->forum->getId()]
                    )
                ); ?>
            <?php endif; ?>
            <?php $discussions = $this->discussion()->getArchivedDiscussions($this->object); ?>
            <?php if (!count($discussions)): ?>
                <div class="alert alert-info"><?php echo $this->translate(
                        'There are no discussions on this topic yet.'
                    ); ?></div>
            <?php endif; ?>
            <?php foreach ($discussions as $discussion): ?>
                <div class="list-group-item">
                    <?php echo $this->partial(
                        'discussion/discussion/show',
                        array('discussion' => $discussion)
                    ); ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>