<?php $form = $this->plugin->getForm('discussion'); ?>
<?php $form->setAttribute('action', $this->url('discussion/discussion/start', array('on' => $this->object->getId()))); ?>
<div class="list-group">  
    <?php if(!$this->isArchived): ?>
        <div class="list-group-item">
            <h4><?php echo $this->translate('Start a new discussion'); ?></h4>
            <hr>
            <?php $form->prepare(); ?>
            <?php $form->setData(array('forum' => $this->plugin->getForum()->getId())); ?>
            <?php echo $this->form()->render($form, null); ?>
        </div>
    <?php endif; ?>
    <?php foreach($this->discussions as $discussion): ?>
        <div  class="list-group-item">
            <?php echo $this->partial('discussion/discussion/show', array('discussion' => $discussion, 'user' => $this->user, 'plugin' => $this->plugin)); ?>
        </div>
    <?php endforeach; ?>
</div>