<?php $name = $this->entity->getType()->getName(); ?>
<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity; ?>
<?php if($this->resolver('entity/view/minimalistic/'.$name)):?>
        <?php echo $this->partial('entity/view/minimalistic/'.$name, array('entity' => $entity)); ?>
    <?php else: ?>
        <?php if($entity->hasCurrentRevision()): ?>
            <?php echo $entity->getCurrentRevision()->get('title'); ?> <small><i><?php echo $entity->getType()->getName(); ?></i></small>
        <?php else: ?>
            <?php echo $this->translate('Pending review:'); ?> <?php echo $entity->getId(); ?> <small><i><?php echo $entity->getType()->getName(); ?></i></small>
        <?php endif; ?>
<?php endif; ?>