<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$exercise = $this->exercise;
?>
<?php if($exercise->repository()->hasCurrentRevision()): ?>
<article class="text-exercise">
	<section class="scope">
        <?php $revision = $exercise->repository()->getCurrentRevision(); ?>
        <?php echo $revision->get('content'); ?>
    </section>
	<section class="solution">
    	<?php if(!is_object($exercise->solution()->findChild())): ?>
    	<?php echo $this->translate(sprintf('Zu dieser Aufgabe gibt es noch keine Lösung. Möchtest du eine Lösung <a href="%s">hinzufügen</a>?', $this->url('entity/create', array('action' => 'create', 'type' => 'text-solution'), array('query' => array('scope' => 'exercise', 'to_entity' => $exercise->getId()))))); ?>
    	<?php else: ?>
    	<?php $solutionRepository = $exercise->solution()->findChild()->repository(); ?>
    	<?php if($solutionRepository->hasHead()): ?>
        <?php echo $solutionRepository->getCurrentRevision()->get('content'); ?>
    	<?php endif; ?>
        <?php endif; ?>
    </section>
</article>
<?php endif; ?>