<ul class="nav nav-tabs">
	<li class="active"><a href="#display" data-toggle="tab"><?php echo $this->translate('Revision'); ?> (#<?php echo $this->revision->getId();?>)</a></li>
	<?php if($this->currentRevision){ ?>
	<li><a href="#current" data-toggle="tab"><?php echo $this->translate('Aktuelle Revision'); ?> (#<?php echo $this->currentRevision->getId();?>)</a></li>
	<?php } ?>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="display">
		<article>
            <?php echo $this->partial('learning-resource/plugin/repository/revision', array('revision' => $this->revision)); ?>
            <?php if($this->revision !== $this->currentRevision): ?>
			<hr>
			<footer>
				<div class="btn-group">					
				    <?php if($this->isGranted('route:entity/plugin/repository/checkout')): ?>
					   <a class="btn btn-success btn-small" href="<?php echo $this->url('entity/plugin/repository',array('action' => 'checkout', 'entity' => $this->entity->getId(), 'revision' => $revision->getId())); ?>"><?php echo $this->translate('Akzeptieren')?></a>
				    <?php endif; ?>
					<?php if($this->isGranted('route:entity/plugin/repository/trash-revision')) { ?>
					   <a class="btn btn-small" href="<?php echo $this->url('entity/plugin/repository',array('action' => 'trash-revision', 'entity' => $this->entity->getId(), 'revision' => $revision->getId())); ?>"><?php echo $this->translate('Verwerfen')?></a>
				    <?php } ?>
					<?php if($this->isGranted('route:entity/plugin/repository/purge-revision')) { ?>
					   <a class="btn btn-danger btn-small" href="<?php echo $this->url('entity/plugin/repository',array('action' => 'purge-revision', 'entity' => $this->entity->getId(), 'revision' => $revision->getId())); ?>"><?php echo $this->translate('Löschen')?></a>
				    <?php } ?>
				</div>
			</footer>
			<?php endif; ?>
		</article>
	</div>
	<?php if(is_object($this->currentRevision)): ?>
	<div class="tab-pane" id="current">
		<article class="current">
            <?php echo $this->partial('learning-resource/plugin/repository/revision', array('revision' => $this->currentRevision)); ?>
		</article>
	</div>
	<?php endif; ?>
</div>