<article>
    <?php if($this->discussion->isDiscussion()): ?>
        <header>
		<h4><?php echo $this->discussion->getTitle(); ?></h4>
	</header>
	<hr>
    <?php endif; ?>
    <section>
		<div class="row">
			<div class="col-md-2">
				<strong><?php echo $this->discussion->getAuthor()->getUsername(); ?></strong>
				<p class="timeago" title="<?php echo $this->discussion->getDate()->format("Y-m-d H:i:s"); ?>"></p>
			    <hr>
                <div class="btn-group btn-group-x">
                    <?php $vote = ($this->discussion->hasUserVoted($this->user)) ? 'down' : 'up'; ?>    
                    <a
						href="<?php echo $this->url('discussion/vote', array('comment' => $this->discussion->getId(), 'vote' => $vote)); ?>" class="btn btn-xs btn<?php echo ($vote == 'up') ? '-default' : '-success'; ?>"><span
						class="glyphicon glyphicon-chevron-<?php print $vote; ?>"></span> 
                    <b><?php echo $this->discussion->countUpVotes(); ?></b> </a>  
                    <?php if($this->discussion->isDiscussion()): ?>
                        <a
    						href="<?php echo $this->url('discussion/archive', array('comment' => $this->discussion->getId())); ?>" class="btn btn-xs btn-<?php echo ($this->discussion->getArchived()) ? 'primary' : 'default'; ?>"><span
    						class="glyphicon glyphicon-inbox"></span></a> 
					<?php endif;?>
                    <a
						href="<?php echo $this->url('discussion/trash', array('comment' => $this->discussion->getId())); ?>" class="btn btn-xs btn-default dialog" data-content="<?php echo $this->translate('Do you really want to delete this discussion?'); ?>"><span
						class="glyphicon glyphicon-trash"></span></a>        
                </div>
			</div>
			<div class="col-md-10">
                <?php echo $this->discussion->getContent(); ?>
            </div>
		</div>
	</section>
    <?php if($this->discussion->isDiscussion()): ?>
        <section>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-10">
				<hr>
				<div class="list-group">  
                    <?php foreach($this->discussion->getChildren() as $comment): ?>
                        <div class="list-group-item">
                            <?php echo $this->partial('discussion/discussion/show', array('discussion' => $comment, 'user' => $this->user)); ?>
                        </div>
                    <?php endforeach; ?>
                </div>
                <?php if(!$this->discussion->getArchived()): ?>
                    <?php $this->discussion->getForm()->setAttribute('action', $this->url('discussion/comment',array('discussion' => $this->discussion->getId()))); ?>
                    <?php $this->discussion->getForm()->prepare(); ?>
                    <?php echo $this->form()->render($this->discussion->getForm(), null); ?>
                <?php endif; ?>
            </div>
		</div>
	</section>
    <?php endif; ?>
</article>