<article>
	<header>
	    <section class="info">
	        <p>Fach: <?php echo $this->subject; ?></p>
	        <p>Thema: <?php echo $this->topic; ?></p>
	    </section>
	</header>
    <section class="content">
    	Inhalt: <?php echo $this->content; ?>
    </section>
    <article class="solution">
        <b>Lösung</b>
    	<section class="content">
    		 Inhalt: <?php echo $this->solution['content'];?>
    	</section>
    </article>
</article>