<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
 ?>
<li class="term">
    <div class="row-fluid">
        <div class="span9">
            <a class="" href="<?php echo rawurldecode($this->url()->buildWithSubject('topic', array('path' => implode('/', $this->term->getPath())))); ?>"><?php echo $this->term->getName(); ?></a>
        </div>
        <div class="span3 btn-group">
            <a href="<?php echo $this->url('taxonomy/term',array('action' => 'update', 'id' => $this->term->getId() )); ?>" class="btn btn-mini"><i class="icon-pencil"></i></a>
            <div class="btn btn-mini"><i class="icon-plus"></i></div>
            <div class="btn btn-mini btn-inverse"><i class="icon-remove icon-white"></i></div>
        </div>
    </div>
    <ul class="">
        <?php foreach($this->children as $child):?>
            <?php echo $this->partial('taxonomy/default/partial', array('term' => $child, 'children' => $child->getChildren())); ?>
        <?php endforeach; ?>
    </ul>
</li>