<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$exercise = $this->entity;
?>
<?php if($exercise->repository()->hasCurrentRevision()): ?>
<article class="text-exercise">
	<section class="scope">
        <?php $revision = $exercise->repository()->getCurrentRevision(); ?>
        <?php echo $revision->get('content'); ?>
    </section>
	<section class="solution">
    	<?php if(!$exercise->exercises()->hasChildren()): ?>
    	<?php echo $this->translate(sprintf('Für diese Aufgabe gibt es noch keine Unteraufgaben, möchtest du eine Unteraufgabe <a href="%s">hinzufügen</a>?', $this->url('entity/create', array('action' => 'create', 'type' => 'grouped-text-exercise'), array('query' => array('scope' => 'exercises', 'to_entity' => $exercise->getId()))))); ?>
    	<?php else: ?>
    	<?php foreach($exercise->exercises()->findChildren() as $child):?>
    	   <?php echo $this->partial('subject/plugin/topic/entity/text-exercise', array('entity' => $child))?>
    	<?php endforeach; ?>
        <?php endif; ?>
    </section>
</article>
<?php endif; ?>