<?php $event = $this->notification->getEvents()->current(); ?>
<?php $user = $this->normalize()->toTitle($event->getActor()); ?>
<?php $object = $this->normalize()->toTitle($event->getObject()); ?>

<a role="menuitem" tabindex="-1" href="<?php echo $this->normalize()->toUrl($event->getParameter('parent')); ?>">
    <?php echo sprintf($this->translate('<strong>%s</strong> added a new entity to "%s"'), $user, $object); ?>
    <small> - <?php echo $this->timeago()->render($this->notification->getTimestamp()); ?></small>
</a>