<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$name = is_object($this->term) ? $this->term->getTaxonomy()->getName() : 'default';
$template = 'subject/plugin/taxonomy/templates/' . $name;
$forum = $this->subject->getSlug() . '/issues/taxonomy';
$data = array(
    'links' => $this->links,
    'acceptsEntities' => $this->acceptsEntities,
    'subject' => $this->subject,
    'plugin' => $this->plugin,
    'term' => $this->term,
    'terms' => $this->terms
);
?>
<?php if($this->resolver($template)):?>
        <?php echo $this->partial($template, $data); ?>
    <?php else: ?>
        <?php echo $this->partial($this->plugin->getTemplate('taxonomy'), $data); ?>
<?php endif; ?>
<hr>
<div class="tab-content">
    <h3><?php echo $this->translate('Discussions'); ?></h3>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#current" data-toggle="tab"><?php echo $this->translate('Current'); ?></a></li>
        <li><a href="#archived" data-toggle="tab"><?php echo $this->translate('Archived'); ?></a></li>
    </ul>
    <div class="tab-pane active" id="current">
        <?php echo $this->discussion($this->term->getEntity()->getUuidEntity(), $forum, false)->render(); ?>
    </div>
    <div class="tab-pane" id="archived">
        <?php echo $this->discussion($this->term->getEntity()->getUuidEntity(), $forum, true)->render(); ?>
    </div>
</div>