<?php echo $this->pageHeader('Compare revisions')->setSubtitle($this->entity->getUuid())->render(); ?>
<ul class="nav nav-tabs">
	<li class="active"><a href="#display" data-toggle="tab"><?php echo $this->translate('Revision'); ?> (#<?php echo $this->revision->getId();?>)</a></li>
	<?php if($this->currentRevision){ ?>
	<li><a href="#current" data-toggle="tab"><?php echo $this->translate('Aktuelle Revision'); ?> (#<?php echo $this->currentRevision->getId();?>)</a></li>
	<?php } ?>
</ul>
<div class="tab-content clearfix">
	<div class="tab-pane active" id="display">
		<article>
            <?php echo $this->partial('entity/repository/revision', array('revision' => $this->revision, 'plugin' => $this->plugin)); ?>
            <?php if($this->revision !== $this->currentRevision): ?>
    			<footer>
    				<div class="btn-group pull-right">	
    				    <?php if(! $this->revision->isTrashed()):?>				
        				    <?php if($this->guard()->hasAccessToRoute('entity/repository/checkout')): ?>
        					   <a class="btn btn-success btn-sm" href="<?php echo $this->url('entity/repository/checkout',array('entity' => $this->entity->getId(), 'revision' => $this->revision->getId())); ?>"><span class="glyphicon glyphicon-ok"></span></a>
        				    <?php endif; ?>
    				        <?php if($this->guard()->hasAccessToRoute('uuid/trash')) { ?>
        					   <a class="btn btn-danger btn-sm" href="<?php echo $this->url('uuid/trash',array('id' => $this->revision->getId())); ?>"><span class="glyphicon glyphicon-trash"></span></a>
        				    <?php } ?>
    				    <?php else: ?>
        					<?php if($this->guard()->hasAccessToRoute('uuid/restore')) { ?>
        					   <a class="btn btn-success btn-sm" href="<?php echo $this->url('uuid/restore',array('id' => $this->revision->getId())); ?>"><span class="glyphicon glyphicon-refresh"></span></a>
           				    <?php } ?>
    				   <?php endif; ?>
    				</div>
    			</footer>
			<?php endif; ?>
		</article>
	</div>
	<?php if(is_object($this->currentRevision)): ?>
    	<div class="tab-pane" id="current">
    		<article class="current">
                <?php echo $this->partial('entity/repository/revision', array('revision' => $this->currentRevision)); ?>
    		</article>
    	</div>
	<?php endif; ?>
</div>