<?php echo $this->pageHeader('History')->setSubtitle($this->entity->getUuid())->render(); ?>

<table class="table table-striped">
	<thead>
		<tr>
			<th><?php echo $this->translate('#'); ?></th>
			<th><?php echo $this->translate('Current'); ?></th>
			<th><?php echo $this->translate('Author'); ?></th>
			<th><?php echo $this->translate('Timestamp'); ?></th>
		</tr>
	</thead>
    <?php foreach ($this->revisions as $revision): ?>
        <?php $isCurrentRevision = $revision === $this->currentRevision; ?>
        <tr class="revision <?php echo $isCurrentRevision ? 'success' : ''; ?>">
    		<td><?php echo $revision->getId(); ?> (<a
    			href="<?php echo $this->url('entity/repository/compare', array('entity' => $this->entity->getId(), 'revision' => $revision->getId())); ?>"><?php echo $this->translate('show'); ?></a>)</td>
    		<td><?php echo ($isCurrentRevision) ? '<i class="icon-ok"></i>' : ''; ?></td>
    		<td><?php echo $revision->getAuthor()->getUsername(); ?></td>
    		<td><?php echo $this->timeago()->render($revision->getTimestamp());?></td>
	    </tr>
    <?php endforeach; ?>
</table>