<?php if(is_object($this->revision)): ?>
    <article class="revision">
    	<?php foreach($this->revision->getFields() as $field): ?>
    	<section>
            <h3><?php echo $field->getField(); ?></h3>
            <?php
                $content = $field->getValue();
                if ($field->getField() === 'content' ||
                    $field->getField() === 'reasoning') {
                    try {
                        echo $this->markdown()->toHtml($content);
                    } catch (Exception $e) {
                        echo $content;
                    }    
                } else {
                    echo $content;
                }
            ?>
        </section>
        <hr>
    	<?php endforeach; ?>
    </article>
<?php endif; ?>