<div class="row-fluid" style="margin-top: 100px;">
	<div class="span3"></div>
	<div class="span6 row-fluid">
		<div class="span9">
		<input
    		type="text" 
    		data-source="[&quot;Mathe&quot;]"
       		data-items="4"
    		data-provide="typeahead"
    		style="margin: 0 auto;"
		>
		</div>
		<div class="span3">
			<input type="button" class="btn" value="suchen">
		</div>
	</div>
	<div class="span3"></div>
</div>