<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->forminput($this->form->get('id'));
echo $this->forminput($this->form->get('parent'));
echo $this->forminput($this->form->get('weight'));
echo $this->forminput($this->form->get('taxonomy'));
echo $this->formRow($this->form->get('term')->get('name'));
echo $this->formSubmit($this->form->get('submit'));
echo $this->forminput($this->form->get('reset'));
echo $this->form()->closeTag();