<?php /* @var $entity \Entity\Service\EntityServiceInterface */ ?>
<?php $entity = $this->entity;?>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
        <?php echo $this->translate('Editing'); ?> <span class="caret"></span>
    </button>
        <ul class="dropdown-menu" role="menu">
            <?php if($entity->hasPlugin('repository')): ?>
                <!-- Edit Revision -->
                <?php $url = $this->url('entity/plugin/repository/add-revision', array('entity' => $entity->getId())); ?>
                <?php if($this->guard()->hasAccessToUrl($url)): ?>
                    <li>
                        <a href="<?php echo $url; ?>">
                            <span class="glyphicon glyphicon-edit"></span>
                            <?php echo $this->translate('Edit'); ?>
                        </a>
                    </li>
                <?php endif; ?>
                <!-- Versioning history -->
                <?php $url = $this->url('entity/plugin/repository/history',array('entity' => $entity->getId())); ?>
                <?php if($this->guard()->hasAccessToUrl($url)): ?>
                    <li>
                        <a href="<?php echo $url; ?>">
                            <span class="glyphicon glyphicon-time"></span>
                            <?php echo $this->translate('Repository history'); ?>
                            <?php if($entity->plugin('repository')->isUnrevised()): ?>
                                <span class="label label-warning"><?php echo $this->translate('new')?></span>
                            <?php endif; ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
            <?php foreach($entity->getScopesForPlugin('link') as $scope): ?>
                <?php $plugin = $entity->$scope(); ?>
                <?php foreach($plugin->getTypes() as $type => $options): ?>
                    <?php if(($plugin->doesAssociationAllowMultiples() && $plugin->owns($type)) || (!$plugin->doesAssociationAllowMultiples() && !is_object($plugin->findChild()))): ?>
                        <?php $url = $this->url('entity/create', array('action' => 'create', 'type' => $type), array('query' => array($options['inversed_by'] => array('to_entity' => $entity->getId())))); ?>
                        <?php if($this->guard()->hasAccessToUrl($url)): ?>
                        	<li>
                            	<a href="<?php echo $url; ?>">
                                    <span class="glyphicon glyphicon-file"></span>
                                    <?php echo sprintf($this->translate('Add %s'), $type); ?>
                            	</a>
                        	<li>
                    	<?php endif; ?>
                	<?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>
</div>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
        <?php echo $this->translate('Data'); ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <?php if($entity->hasPlugin('license')): ?>
            <!-- License -->
            <?php $url = $this->url('license/detail',array('id' => $entity->license()->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-leaf"></span>
                        <?php echo $this->translate('License'); ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        
        <!-- Event log -->
        <?php $url = $this->url('event/history',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-hdd"></span>
                    <?php echo $this->translate('Eventlog'); ?>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</div>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
        <?php echo $this->translate('Manage'); ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <!-- Flag content -->
        <?php $url = $this->url('flag/add',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-flag"></span>
                    <?php echo $this->translate('Flag content'); ?>                
                </a>
            </li>
        <?php endif; ?>
        
        <?php if($entity->hasPlugin('taxonomy')): ?>
            <!-- Change taxonomy term(s) -->
            <?php $url = $this->url('entity/plugin/taxonomy/update',array('entity' => $entity->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-map-marker"></span>
                        <?php echo $this->translate('Taxonomy terms'); ?>   
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        
        <!-- Manage related content -->
        <?php $url = $this->url('related-content/manage',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-link"></span>
                    <?php echo $this->translate('Related content'); ?>   
                </a>
            </li>
        <?php endif; ?>
        
        <!-- License -->
        <?php if($entity->hasPlugin('license')): ?>
            <?php $url = $this->url('entity/plugin/license/update', array('entity' => $entity->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-leaf"></span>
                        <?php echo $this->translate('Change license'); ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        
        <!-- Trash entity -->
        <?php $url = $this->url('uuid/trash',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-trash"></span>
                    <?php echo $this->translate('Trash'); ?>   
                </a>
            </li>
        <?php endif; ?>
    </ul>
</div>