<?php /* @var $entity \Entity\Entity\EntityInterface */ ?>
<?php $entity = $this->entity;?>
<?php /* @var $options \Entity\Options\EntityOptions */ ?>
<?php $options = $this->entity()->getOptions($entity); ?>
<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
        <?php echo $this->translate('Editing'); ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <?php if($options->hasComponent('repository')): ?>
            <!-- Edit Revision -->
            <?php $url = $this->url('entity/repository/add-revision', array('entity' => $entity->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-edit"></span>
                        <?php echo $this->translate('Edit'); ?>
                    </a>
                </li>
            <?php endif; ?>
            <!-- Versioning history -->
            <?php $url = $this->url('entity/repository/history',array('entity' => $entity->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-time"></span>
                        <?php echo $this->translate('Repository history'); ?>
                        <?php if($entity->isUnrevised()): ?>
                            <span class="label label-warning"><?php echo $this->translate('new')?></span>
                        <?php endif; ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        <?php if($options->hasComponent('link')): ?>
            <?php /* @var $componentOptions \Entity\Options\LinkOptions */ ?>
            <?php $componentOptions = $options->getComponent('link'); ?>
            <?php foreach($componentOptions->getAllowedChildren() as $type): ?>
                <?php if($componentOptions->allowsManyChildren($type) || (!$componentOptions->allowsManyChildren($type) && $entity->getChildren('link')->count() < 1)): ?>
                    <?php $url = $this->url('entity/create', ['type' => $type], ['query' => ['link' => ['type' => 'link', 'child' => $entity->getId()]]]); ?>
                    <?php if($this->guard()->hasAccessToUrl($url)): ?>
                    	<li>
                        	<a href="<?php echo $url; ?>">
                                <span class="glyphicon glyphicon-file"></span>
                                <?php echo sprintf($this->translate('Add %s'), $type); ?>
                        	</a>
                    	<li>
                	<?php endif; ?>
            	<?php endif; ?>
            <?php endforeach; ?>
    	<?php endif; ?>
        </ul>
</div>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
        <?php echo $this->translate('Data'); ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <?php if($options->hasComponent('license')): ?>   
            <!-- License -->
            <?php $url = $this->url('license/detail',array('id' => $entity->getLicense()->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-leaf"></span>
                        <?php echo $this->translate('License'); ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        
        <!-- Event log -->
        <?php $url = $this->url('event/history',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-hdd"></span>
                    <?php echo $this->translate('Eventlog'); ?>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</div>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
        <?php echo $this->translate('Manage'); ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <!-- Flag content -->
        <?php $url = $this->url('flag/add',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-flag"></span>
                    <?php echo $this->translate('Flag content'); ?>                
                </a>
            </li>
        <?php endif; ?>
        
        <?php if($options->hasComponent('link')): ?>
            <?php foreach($entity->getParents('link') as $parentLink):?>
                <!-- Change parents -->
                <?php $url = $this->url('entity/link/move',array('entity' => $entity->getId(), 'from' => $parentLink->getId(), 'type' => 'link')); ?>
                <?php if($this->guard()->hasAccessToUrl($url)): ?>
                    <li>
                        <a href="<?php echo $url; ?>">
                            <span class="glyphicon glyphicon-map-marker"></span>
                            <?php echo sprintf($this->translate('Change parent "%s"'), $parentLink->getType()->getName()); ?>   
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?> 
        <?php endif; ?>
        
        <?php if($options->hasComponent('taxonomy')): ?>   
            <!-- Change taxonomy term(s) -->
            <?php $url = $this->url('entity/taxonomy/update',array('entity' => $entity->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-map-marker"></span>
                        <?php echo $this->translate('Taxonomy terms'); ?>   
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        
        <!-- Manage related content -->
        <?php $url = $this->url('related-content/manage',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-link"></span>
                    <?php echo $this->translate('Related content'); ?>   
                </a>
            </li>
        <?php endif; ?>
        
        <!-- License -->
        <?php if($options->hasComponent('license')): ?>   
            <?php $url = $this->url('entity/license/update', array('entity' => $entity->getId())); ?>
            <?php if($this->guard()->hasAccessToUrl($url)): ?>
                <li>
                    <a href="<?php echo $url; ?>">
                        <span class="glyphicon glyphicon-leaf"></span>
                        <?php echo $this->translate('Change license'); ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
        
        <!-- Trash entity -->
        <?php $url = $this->url('uuid/trash',array('id' => $entity->getId())); ?>
        <?php if($this->guard()->hasAccessToUrl($url)): ?>
            <li>
                <a href="<?php echo $url; ?>">
                    <span class="glyphicon glyphicon-trash"></span>
                    <?php echo $this->translate('Trash'); ?>   
                </a>
            </li>
        <?php endif; ?>
    </ul>
</div>