<?php
$user       = $this->normalize()->toAnchor($this->event->getActor());
$revision   = $this->normalize()->toAnchor($this->event->getObject());
$repository = $this->event->getParameter('repository');
$entity     = '<strong>' . $this->translate('trashed content') . '</strong>';
if ($repository) {
    $entity = $this->normalize()->toAnchor($repository);
}
echo sprintf($this->translate('%s created a new version of %s'), $user, $entity);