<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="row-fluid">
	<div class="span3">
        <ul class="nav nav-list nav-stacked affix">
            <?php foreach($this->items as $item):?>
	        <?php echo $this->partial('layout/sidenav/partial',array('item' => $item)); ?>
            <?php endforeach;?>   
        <?php
            
	                            echo $this->navigation('navigation')
	                                    ->menu()
	                                    ->setOnlyActiveBranch(true)
	                                    ->setMinDepth(1)
	                                    ->setMaxDepth(2)
	                                    ->setUlClass('nav nav-tabs')
	                                    ->setPartial('layout/sidenav/vertical-nav')
	                                    ->render();
            ?>
        </ul>
	</div>
	<div class="span9">
		<?php echo $this->content; ?>
	</div>
</div>