<?php
/**
* @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg; Timo Klement
*/
$html = array();
//$html[] = '<div class="navbar navbar-fixed-top">';
//$html[] = ' <div class="navbar-inner">';
//$html[] = ' <div class="container">';
//$html[] = ' <ul class="nav">';

foreach ($this->container as $page) {
    // visibility of the page
    if (! $page->isVisible() || (! $page->isActive(true))) {
        continue;
    }
    
    // dropdown
    $dropdown = ! empty($page->pages);
    
    
    //$html[] = '<ul class="dropdown-vertical-nav">';
    
    foreach ($page->pages as $subpage) {
        // visibility of the sub-page
        if (! $subpage->isVisible()) {
            continue;
        }
        if ($subpage->getLabel() == 'divider') {
            $html[] = '<li class="divider"></li>';
            continue;
        }
        $html[] = '<li class="' . ($subpage->isActive() ? 'active' : '') .'">';
        $html[] = '<a href="' . $subpage->getHref() . '">';
        
        $html[] = $subpage->getLabel();
        $html[] = "</a>";
        
    }    
    $html[] = "</li>";
}

echo join(PHP_EOL, $html);