<?php echo $this->pageHeader('Pages')->render(); ?>

<div class="list-group">
    <?php foreach ($this->pages as $page) : ?>
        <div class="list-group-item">
            <a href="<?php echo $this->url('page/view', array('page' => $page->getId())); ?>">
                <?php echo $page->hasCurrentRevision() ? $page->getCurrentRevision()->getTitle() :
                    $this->translate('No revision checked out yet.'); ?>
            </a>
            <hr>
            <div class="btn-group">
                <a class="btn btn-xs btn-default" href="<?php echo $this->url(
                    'page/update',
                    array('page' => $page->getId())
                ); ?>"><span class="glyphicon glyphicon-edit"></span>
                    <?php echo $this->translate('Edit'); ?>
                </a>
                <a class="btn btn-xs btn-default"  href="<?php echo $this->url(
                    'uuid/trash',
                    array('id' => $page->getId())
                ); ?>"><span class="glyphicon glyphicon-remove"></span>
                    <?php echo $this->translate('delete'); ?>
                </a>
            </div>
        </div>
    <?php endforeach; ?>
    <a class="list-group-item" href="<?php echo $this->url('page/create'); ?>">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Create a new page'); ?>
    </a>
</div>