<?php echo $this->pageHeader('Pages')->render(); ?>

<div class="list-group">
    <?php foreach ($this->repositorys as $repository) : ?>
        <a class="list-group-item"
           href="<?php echo $this->url('page/view', array('repository' => $repositoryid)); ?>">
            <?php
            if ($repository->hasCurrentRevision()) {
                echo $repository->getCurrentRevision()->getTitle();
            } else {
                echo $this->translate('no current revision set');
            }
            ?>
        </a> <a href="<?php echo $this->url(
            'page/view/editrepository',
            array('repository' => $repository->getId())
        ); ?>" class="glyphicon glyphicon-edit"><?php echo $this->translate('edit'); ?></a>
        <a href="<?php echo $this->url(
            'page/view/deleterepository',
            array('repository' => $repository->getId())
        ); ?>" class="glyphicon glyphicon-remove"><?php echo $this->translate('delete'); ?></a>
        <br>
        <br>
    <?php endforeach; ?>
    <a class="list-group-item" href="<?php echo $this->url('page/create'); ?>">
        <span class="glyphicon glyphicon-plus"></span><?php echo $this->translate('Create a new page'); ?></a>
</div>