
<a href="<?php echo $this->url('page/createrepository')?>"><button class="btn btn-xs btn-info" type="button">Neue Seite</button></a>

<a href="<?php echo $this->url('page/article/editrepository',array('slug'=>$slug))?>"><button class="btn btn-xs btn-info" type="button">Seite bearbeiten</button></a>

<a href="<?php echo $this->url('page/article/deleterepository',array('slug'=>$slug))?>"><button class="btn btn-xs" type="button">Seite löschen</button></a><br>
