<a href="<?php echo $this->url('page/article/createrevision',array('slug'=>$slug,'id'=>$id))?>"><button class="btn btn-xs btn-primary" type="button">Neue Revision</button></a>
<a href="<?php echo $this->url('page/article/revisions',array('slug'=>$slug))?>"><button class="btn btn-xs btn-primary" type="button">Revisionen Verwalten</button></a>
<a href="<?php if ($id!=null) echo $this->url('page/article/deleterevision',array('slug'=>$slug,'revisionid'=>$id))?>"><button class="btn btn-xs" type="button">Revision löschen</button></a>
