<?php
if ($this->revision != NULL)
    $id = $this->revision->getId();
else {
    $id = $this->revision = '';
}
?>

<!-- Only Visible for if User has Permission -->
<?php if ($this->rbac()->hasAccessToRoute('page/article/createrevision')): ?>

<div class="btn-group">
	<a
		href="<?php echo $this->url('page/article/createrevision',array('slug'=>slug,'id'=>$id))?>"
		class="btn btn-link glyphicon glyphicon-file">edit</a> <a
		href="<?php echo $this->url('page/article/revisions',array('slug'=>$this->slug))?>"
		class="btn btn-link glyphicon glyphicon-align-left"><?php echo $this->translate('revisions'); ?></a> 
		<?php if ($this->revision!=''&&$this->revision->getRepository()->getCurrentRevision()!=$this->revision): ?>
		<a
		href="<?php if ($id!=null) echo $this->url('page/article/deleterevision',array('slug'=>$this->slug,'revisionid'=>$id))?>"
		class="btn btn-link glyphicon glyphicon-remove"><?php echo $this->translate('delete'); ?></a>
	<a
		href="<?php echo $this->url('page/article/revision/setCurrent',array('slug'=>$this->slug,'id'=>$id))?>"
		class="btn btn-link glyphicon glyphicon-ok"><?php echo $this->translate('set current'); ?></a>

<?php endif;?>
</div>
<?php endif;