<?php if ($this->revision && $this->isGranted('page.revision.create', $this->revision)): ?>
    <?php $id = $this->revision->getId(); ?>
    <!-- Only Visible for if User has Permission -->
    <div class="btn-group">
        <a href="<?php echo $this->url(
            'page/view/createrevision',
            array('repository' => $this->repositoryid->getId(), 'id' => $id)
        ) ?>" class="btn btn-link glyphicon glyphicon-plus">edit</a> <a href="<?php echo $this->url(
            'page/view/revisions',
            array('repository' => $this->repositoryid->getId())
        ) ?>" class="btn btn-link glyphicon glyphicon-align-left"><?php echo $this->translate('revisions'); ?>
        </a>
        <?php if ($this->revision != '' && $this->revision->getRepository()->getCurrentRevision() != $this->revision
        ): ?>
            <a href="<?php echo $this->url(
                'page/view/deleterevision',
                array('repository' => $this->repositoryid->getId(), 'revisionid' => $id)
            ); ?>" class="btn btn-link glyphicon glyphicon-remove"><?php echo $this->translate('trash'); ?></a>
            <a href="<?php echo $this->url(
                'page/view/revision/setCurrent',
                array('repository' => $this->repositoryid->getId(), 'id' => $id)
            ) ?>" class="btn btn-link glyphicon glyphicon-ok"><?php echo $this->translate('setCurrent'); ?></a>

            <a href="<?php echo $this->url('page/view', array('repository' => $this->repositoryid->getId())); ?>"
               class="glyphicon glyphicon-star btn btn-link"><?php echo $this->translate('current'); ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>