

<?php
$title2 = 'Page ';
$this->headTitle($title2);
?>

<?php //Show Repository Menu?>
<?php


echo $this->partial('page/repository-menu.phtml', array(
    'slug' => $slug
));
?><br>

<?php foreach ($this->revisions as $revision) { ?>
<article>
<?php $id = $revision->getId();?>

<a
		href="<?php echo $this->url('page/article/revision',array('slug'=>$slug,'id'=>$id));?>">

		<button class="btn btn-xs btn-success" type="button">
 Title: 
	<?php
    
$title = $revision->getTitle();
    if ($title != NULL)
        echo $this->escapeHtml($title);
    ?> 
</button>


	</a>
 Date:
	<?php
    
$date = $revision->getDate();
    if ($date != NULL)
        echo $this->escapeHtml($date->format('Y-m-d H:i:s'));
    ?> 
	</a> <a
		href="<?php echo $this->url('page/article/createrevision',array('slug'=>$slug,'id'=>$id))?>">
		<button class="btn btn-xs btn-info" type="button">Revision Barbeiten</button>
	</a> <a
		href="<?php echo $this->url('page/article/deleterevision',array('slug'=>$slug,'revisionid'=>$id))?>"><button
			class="btn btn-xs btn-info" type="button">Revision löschen</button></a>
	<a
		href="<?php echo $this->url('page/article/revision/setCurrent',array('slug'=>$slug,'id'=>$id))?> "><button
			class="btn btn-xs btn-success" type="button">Als Aktuelle Revision
			setzen</button></a> <br>
</article>

<?php } ?><br>
<a href="<?php echo $this->url('page/article',array('slug'=>$slug));?>"><button
		class="btn btn-xs btn-primary" type="button">Aktuelle Revision</button></a>
<a
	href="<?php echo $this->url('page/article/createrevision',array('slug'=>$slug,'id'=>null))?>"><button
		class="btn btn-xs btn-primary" type="button">Neue Revision</button></a>
<br>
