<?php
$this->headTitle($slug);
?>

<?php //Show Repository Menu
echo $this->partial('page/repository-menu.phtml', array(
    'slug' => $slug
));
?>

<article>

 Author:
	<?php

$id = $revision->getId();
if ($author != NULL)
    echo $this->escapeHtml($author);
?> 

 Date:
	<?php

$date = $revision->getDate();
if ($date != NULL)
    echo $this->escapeHtml($date->format('Y-m-d H:i:s'));
?> 
	<br>
	
	
<?php // Show Revision Title & Content
echo $this->partial('page/revision-partial.phtml', array(
    'title' => $revision->getTitle(),
    'content' => $revision->getContent()
));
?>
	 
	
	<br>
</article>

<?php //Show Revision Menu?>
<a
	href="<?php echo $this->url('page/article/revision/setCurrent',array('slug'=>$slug,'id'=>$id))?>">
	<butto class="btn btn-xs btn-success" type="button"> Als Aktuelle
	Revision setzen
	</button>

</a>
<?php

echo $this->partial('page/revision-menu.phtml', array(
    'slug' => $slug,
    'id' => $id
));
?>

<br>
