<?php
/* @var $entity \Entity\Entity\EntityInterface */
$entity = $this->entity;
$options = $this->entity()->getOptions($entity);
?>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-<?php echo $entity->getId(); ?>">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-<?php echo $entity->getId(); ?>">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="#">
                        <span class="glyphicon glyphicon-eye-open"></span>
                        <?php echo $this->translate('View'); ?>
                    </a>
                </li>
                <?php echo $this->partial('entity/view/partials/actions/versioning/edit', ['entity' => $entity]); ?>
                <?php echo $this->partial('entity/view/partials/actions/versioning/history', ['entity' => $entity]); ?>
                <?php echo $this->partial('entity/view/partials/actions/license/show', ['entity' => $entity]); ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->translate('More'); ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php echo $this->partial('entity/view/partials/actions/link/add', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/link/update', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/taxonomy/update', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/related-content/manage', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/license/update', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/flag/create', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/event/history', ['entity' => $entity]); ?>
                        <?php echo $this->partial('entity/view/partials/actions/trash', ['entity' => $entity]); ?>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>