<?php
/* @var $entity \Entity\Entity\EntityInterface */
$entity = $this->entity;
?>

<?php echo $this->partial('entity/view/partials/actions/versioning/edit', ['entity' => $entity]); ?>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php echo $this->partial('entity/view/partials/actions/versioning/history', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/license/show', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/link/add', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/link/update', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/taxonomy/update', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/related-content/manage', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/license/update', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/flag/create', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/event/history', ['entity' => $entity]); ?>
        <?php echo $this->partial('entity/view/partials/actions/trash', ['entity' => $entity]); ?>
    </ul>
</li>