<?php if($this->rbac()->hasAccessToRoute('entity/plugin/link/order')): ?>
    <button class="btn btn-sm btn-default sortable-activate-action">
        <span class="glyphicon glyphicon-sort"></span>
    </button>
    <button class="btn btn-sm btn-success sortable-save-action is-hidden">
        <span class="glyphicon glyphicon-floppy-save"></span>
    </button>
    <button class="btn btn-sm btn-default sortable-abort-action is-hidden">
        <span class="glyphicon glyphicon-remove"></span>
    </button>
<?php endif; ?>