<li class="dropdown">
    <a data-toggle="dropdown" class="dropdown-toggle" href="#" data-trigger="ping" data-href="<?php echo $this->url('notification/read'); ?>">
        <span class="glyphicon glyphicon-bell"></span>
        <?php $seen = $this->notifications()->getSeen($this->notifications); ?>
        <?php echo $this->translate('Notifications'); ?>
        <?php if($seen->count()): ?>
            <span class="label label-info"><?php echo $seen->count(); ?></span>
        <?php endif; ?>
    </a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <?php if (count($this->notifications) == 0): ?>
            <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#"><?php echo sprintf(
                        $this->translate('You have no notifications.')
                    ); ?></a></li>
        <?php else: ?>
            <?php foreach ($this->notifications as $notification): ?>
                <?php //todo this is a very ugly hack */ ?>
                <?php if($notification->getEvents()->current() && $this->isGranted('event.log.get', $notification->getEvents()->current())): ?>
                    <li role="presentation" class="<?php $notification->getSeen() ? '' : 'active ' ?>">
                        <?php echo $this->partial('user/notification/notification', ['notification' => $notification]); ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</li>