<?php $notification = $this->notification; ?>
<?php $name = $notification->getEventName(); ?>
<?php if ($this->resolver('user/notification/type/' . $name)): ?>
    <?php echo $this->partial(
        'user/notification/type/' . $name,
        array('notification' => $notification)
    ); ?>
<?php else: ?>
    <a role="menuitem" tabindex="-1" href="#">
        <?php echo sprintf(
            $this->translate('Event %s, User %s, Uuid %s'),
            $name,
            $notification->getActors()->current()->getUsername(),
            $notification->getObjects()->current()->getId()
        ); ?>
        <small><?php echo $this->timeago()->render($notification->getEvents()->current()->getTimestamp()); ?></small>
    </a>
<?php endif; ?>