<?php
/**
 *
* Athene2 - Advanced Learning Resources Manager
*
* @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
* @license	LGPL-3.0
* @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
* @link		https://github.com/serlo-org/athene2 for the canonical source repository
* @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
*/
$classes = array();

if (! isset($this->isChild)) : ?>
<div class="sortable"
	data-action="/restricted/taxonomy/term/order/<?php print $this->term->getId(); ?>">
	<div class="clearfix"></div>
    <?php echo $this->partial('taxonomy/taxonomy/actions', array('term' => $term)); ?>
    <hr>
<?php endif; ?>
    <ol id="<?php echo $this->term->getId(); ?>" class="dd-list"
		data-id="<?php echo $this->term->getId(); ?>">
        <?php foreach($this->term->getChildren() as $term):?>
            <li class="dd-item term"
			data-id="<?php echo $term->getId(); ?>">
			<div class="term-inner">
				<span class="dd-handle sort-handle"><i
					class="glyphicon glyphicon-resize-vertical"></i></span>
                        <?php echo $term->getName(); ?>
                        <?php echo $this->partial('taxonomy/taxonomy/actions', array('term' => $term)); ?>
                </div>
                <?php echo $this->partial('taxonomy/taxonomy/partial', array('term' => $term, 'isChild' => true)); ?>
            </li>
        <?php endforeach; ?>
    </ol>
<?php if (!isset($this->isChild)) : ?>
    <div class="list-actions">
		<button class="btn btn-success save-order is-hidden"><?php print $this->translate('Reihenfolge speichern'); ?></button/>
	</div>
</div>
<?php endif; ?>