<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author        Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license        LGPL-3.0
 * @license        http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link                https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<?php if(!isset($this->isChild)): ?>
<?php echo $this->pageHeader('Assign a resource')->render(); ?>
<form method="post"
	action="<?php $this->url('entity/taxonomy/update', array('entity' => $this->entity->getId())); ?>">
	<input type="hidden" name="ref" value="<?php echo $this->ref; ?>" />
<?php endif; ?>
<ul>
    <?php /* @var $term \Taxonomy\Entity\TaxonomyTermInterface */ ?>
    <?php foreach($this->terms as $term):?>
        <li class="term">
            <?php if($this->taxonomy()->getOptions($term)->isAssociationAllowed('entities')): ?>
                <input type="hidden" name="terms[<?php echo $term->getId(); ?>]" value="0" />
    			<input type="checkbox" name="terms[<?php echo $term->getId(); ?>]" value="1"
        			<?php echo $term->isAssociated('entities', $this->entity) ? 'checked="checked"' : '';?> />
			<?php endif; ?>
            <?php echo $term->getName(); ?>
            <?php echo $this->partial('/entity/taxonomy/update', array('entity' => $this->entity, 'terms' => $term->getChildren(), 'isChild' => true)); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php if(!isset($this->isChild)): ?>
<input type="submit" name="submit" value="submit"
		class="btn btn-success" />
</form>
<?php endif; ?>