<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<table class="table table-hover">
    <thead>
        <tr>
            <td>#</td>
            <td><?php echo $this->translate('Benutzername'); ?></td>
            <td><?php echo $this->translate('E-Mail-Adresse'); ?></td>
            <td><?php echo $this->translate('Rollen'); ?></td>
            <td><?php echo $this->translate('Vorname'); ?></td>
            <td><?php echo $this->translate('Nachname'); ?></td>
            <td><?php echo $this->translate('Geschlecht'); ?></td>
            <td><?php echo $this->translate('Letzter Login'); ?></td>
            <td><?php echo $this->translate('Anzahl der Logins'); ?></td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->users as $user): ?>
            <tr>
                <td><?php echo $user->getId(); ?></td>
                <td><?php echo $user->getUsername(); ?></td>
                <td><?php echo $user->getEmail(); ?></td>
                <td>
                    <dl>  
                        <?php foreach($user->getRoles() as $role):?>
                            <dd class="dropdown">
                                <a class="dropdown-toggle btn btn-small btn-link" data-toggle="dropdown" href="#"><?php echo $role->getName(); ?> <b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                    <li><a href="<?php echo $this->url('restricted/user/role', array('action' => 'remove', 'user' => $user->getId(), 'role' => $role->getId()));?>"><?php echo $this->translate('Rolle entziehen'); ?></a></li>
                                </ul>
                            </dd>
                        <?php endforeach; ?>
                        <dd><a class="btn btn-small btn-link" href="<?php echo $this->url('restricted/user/role', array('action' => 'add', 'user' => $user->getId()));?>"><?php echo $this->translate('Rolle zuweisen'); ?></a></dd>                
                    </dl>
                </td>
                <td><?php echo $user->getGivenName(); ?></td>
                <td><?php echo $user->getLastName(); ?></td>
                <td><?php echo $user->getGender(); ?></td>
                <td><?php echo $user->getLastLogin() ? $user->getLastLogin()->format('H:i:s s-m-Y') : $this->translate('Nie'); ?></td>
                <td><?php echo $user->getLogins(); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>