<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$subtitle = is_object($this->topic) ? $this->topic->getName() : NULL;
$this->renderTitle($this->translate('Themenübersicht'), NULL, $subtitle);
?>
<div class="accordion" id="accordion">
<?php
foreach ($topics as $topic) {
    $children = $topic->getChildren();
    ?>
    <div class="accordion-group">
		<div class="accordion-heading">
    		<?php if(1 != 0){ /* $children->count() */?>
    			<a class="accordion-toggle"
				href="<?php echo $this->url('math/topic', array('path' => implode('/', $topic->getPath()))); ?>"><?php echo $topic->getName(); ?></a>
            <?php } else {?>
			<a class="accordion-toggle" data-toggle="collapse"
				data-parent="#accordion"
				href="#collapse<?php echo $topic->getId(); ?>"><?php echo $topic->getName(); ?></a>
    	   <?php } ?>
    			</div>
    <?php
    foreach ($children as $child) {
        ?> 
		<div id="collapse<?php echo $topic->getId(); ?>"
			class="accordion-body collapse in">
			<div class="accordion-inner">
				<a class="accordion-toggle"
					href="<?php echo $this->url('math/topic', array('path' => implode('/', $child->getPath()))); ?>"><?php echo $child->getName(); ?></a>
			</div>
		</div>
        <?php
    }
    ?>
    </div>
    <?php
}
?>
</div>
<?php if (isset($this->entities)): ?>
<div class="content">
    <?php echo $this->partialLoop('subject/math/partials/entity', $this->entities)->setObjectKey('model'); ?>
</div>
<?php endif; ?>