<?php $blog = $this->post->getBlog(); ?>
<?php $blogUrl = $this->normalize()->toUrl($blog); ?>
<article>
    <header class="page-header">
        <h1>
            <?php echo $this->post->getTitle(); ?>
            <small>
                <?php echo $this->translate(sprintf(
                    'by %s <small>%s</small>',
                    $this->post->getAuthor()->getUsername(),
                    $this->timeago()->render($this->post->getTimestamp())
                )); ?>
            </small>
        </h1>
    </header>
    <?php echo $this->markdown()->toHtml($this->post->getContent()); ?>
    <hr/>
    <footer>
        <nav>
            <?php echo $this->translate(sprintf('&#8592 Return to %s', "<a href=\"{$blogUrl}\">{$blog->getName()}</a>")); ?>
        </nav>
    </footer>
</article>