<?php // if($this->guard()->hasAccessToRoute('entity/plugin/link/order')): ?>
<?php if ($this->isGranted('taxonomy.term.associated.sort', $this->term)): ?>
    <button class="btn btn-xs btn-default sortable-activate-action">
        <span class="glyphicon glyphicon-sort"></span>
    </button>
    <button class="btn btn-xs btn-success sortable-save-action is-hidden">
        <span class="glyphicon glyphicon-floppy-save"></span>
    </button>
    <button class="btn btn-xs btn-default sortable-abort-action is-hidden">
        <span class="glyphicon glyphicon-remove"></span>
    </button>
<?php endif; ?>