<article>
    <div class="pull-right btn-group">
        <?php $url = $this->url('entity/create', array('action' => 'create', 'type' => 'grouped-text-exercise'), array('query' => array('group' => array('to_entity' => $this->entity->getId())))); ?>
        <?php if($this->rbac()->hasAccessToUrl($url)): ?>
        	<a class="btn btn-default btn-xs"
        		href="<?php echo $url; ?>">
        		<strong>+</strong>
        	</a>
    	<?php endif; ?>
        <?php echo $this->partial('learning-resource/view/partials/actions', array('entity' => $this->entity, 'hide' => $this->hideActions)); ?>
    </div>
    <section>
        <?php if($this->entity->repository()->hasCurrentRevision()): ?>
            <?php echo  $this->entity->repository()->getCurrentRevision()->get('content'); ?>
        <?php endif; ?>
    </section>
    <section>
    	<ol>
        	<?php foreach($this->entity->exercises()->findChildren() as $child):?>
                <li><?php echo $this->partial('learning-resource/view/default', array('entity' => $child, 'parent' => $this->entity, 'hideActions' => array('detail'))); ?></li>
        	<?php endforeach; ?>
        </ol>
    </section>
</article>