<div class="pull-right btn-group">
    <?php echo $this->partial('learning-resource/view/partials/actions', array('entity' => $this->entity, 'hide' => $this->hideActions)); ?>
</div>
<section>
    <?php if($this->entity->repository()->hasCurrentRevision()): ?>
        <?php echo  $this->entity->repository()->getCurrentRevision()->get('content'); ?>
    <?php endif; ?>
</section>  
<div class="clearfix"></div>