
<article>
	<header>
		<h1 class="page_header"><?php echo $this->title; ?></h1>
	</header>
	<?php echo $this->content; ?>
	<hr>
	<section>
        <div class="tab-content">
            <h3><?php echo $this->translate('Discussions'); ?></h3>
            <ul class="nav nav-tabs">
                <li class="active"><a href="#current" data-toggle="tab"><?php echo $this->translate('Current'); ?></a></li>
                <li><a href="#archived" data-toggle="tab"><?php echo $this->translate('Archived'); ?></a></li>
            </ul>
            <div class="tab-pane active" id="current">
    	       <?php echo $this->partial($this->discussion->getTemplate(), array('plugin' => $this->discussion, 'isArchived' => false, 'discussions' => $this->discussion->getDiscussions(false), 'entity' => $this->entity, 'user' => $this->user)); ?>
	           </div>
            <div class="tab-pane" id="archived">
    	       <?php echo $this->partial($this->discussion->getTemplate(), array('plugin' => $this->discussion, 'isArchived' => true, 'discussions' => $this->discussion->getDiscussions(true), 'entity' => $this->entity, 'user' => $this->user)); ?>
	       </div>
        </div>
	</section>
</article>