<article>
    <header class="page-header">
        <h1><?php echo $this->translate('Exercise group'); ?></h1>
    </header>
    <section>
        <?php echo $this->entity->repository()->getCurrentRevision()->get('content'); ?>
    </section>
    <section>
        <div class="sortable" data-action="<?php echo $this->url('entity/plugin/link/order', array('scope' => 'exercises', 'entity' => $this->entity->getId())); ?>" data-depth="1">
            <ol class="sortable-list">
                <?php foreach($this->entity->exercises()->findChildren() as $child): ?>
                    <?php if($child->repository()->hasCurrentRevision()): ?>
                        <li class="sortable-item" data-id="<?php echo $child->getId(); ?>">
                            <div class="sortable-item-inner sortable-handle">
                                <article>
                                    <?php echo $child->repository()->getCurrentRevision()->get('content'); ?>
                                </article>
                            </div>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
            <div class="sortable-actions">
                <button class="btn btn-success sortable-save-action is-hidden">
                    <?php echo $this->translate('save'); ?>
                </button>
            </div>
        </div>
    </section>
</article>