<article class="module">
	<header class="page-header">
        <div class="pull-right btn-group">
            <?php echo $this->partial('subject/plugin/taxonomy/entity/interaction', array('entity' => $this->entity)); ?>
        </div>
		<h1>
			<div class="row">
				<div class="col-md-11">
		          <?php echo $this->title; ?> <small><?php echo $this->translate('Module'); ?></small>
				</div>
				<div class="col-md-1">
				</div>
			</div>
		</h1>
	</header>
	<section>
        <div class="list-group">
            <?php foreach($this->pages as $page):?>
                <?php if($page->plugin('repository')->hasCurrentRevision() && !$page->getTrashed()):?>
                    <?php $revision = $page->plugin('repository')->getCurrentRevision();?>
                    <a class="list-group-item" href="<?php echo '#'.$page->getId(); ?>">
                        <h4 class="list-group-item-heading"><span class="glyphicon glyphicon-align-left"></span> <?php echo $revision->get('title'); ?></h4>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
    		<a class="list-group-item"
    			href="<?php echo $this->url('entity/create', array('type' => 'module-page'), array('query' => array('module' => array('to_entity' => $this->entity->getId())))); ?>">
    			<h4 class="list-group-item-heading"><span class="glyphicon glyphicon-file"></span> <?php echo $this->translate('Add a new page'); ?></h4>
    		</a>
    	</div>
	</section>
	<section>
        <?php foreach($this->pages as $page):?>
            <?php if($page->plugin('repository')->hasCurrentRevision() && !$page->getTrashed()):?>
                <?php $revision = $page->plugin('repository')->getCurrentRevision();?>
            	<article class="panel panel-default">
                    <header id="<?php echo $page->getId(); ?>" class="panel-heading">
                        <div class="row">
                            <div class="col-md-10"><?php echo $revision->get('title'); ?></div>
                            <div class="col-md-2">
                                <div class="pull-right btn-group">
                                	<a class="btn btn-default btn-xs"
                                		href="<?php echo $this->url('entity/plugin/repository',array('action' => 'add-revision', 'entity' => $page->getId())); ?>"><span
                                		class="glyphicon glyphicon-edit"></span></a>
                                	<a class="btn btn-default btn-xs<?php echo ($page->plugin('repository')->isUnrevised()) ? ' btn-warning' : ''?>"
                                		href="<?php echo $this->url('entity/plugin/repository',array('action' => 'history', 'entity' => $page->getId())); ?>"><span
                                		class="glyphicon glyphicon-time"></span></a>
                                	<a class="btn btn-default btn-xs"
                                		href="<?php echo $this->url('entity/trash',array('entity' => $page->getId())); ?>"><span
                                		class="glyphicon glyphicon-trash"></span></a>
                                </div>
                            </div>
                        </div>
                    </header>
                    <section class="panel-body">
                        <?php echo $revision->get('content'); ?>
                    </section>
                </article>
            <?php endif; ?>
        <?php endforeach; ?>
	</section>
    <hr>
    <section>
        <?php echo $this->partial($this->discussion->getTemplate('widget'), array('discussion' => $this->discussion, 'entity' => $this->entity, 'user' => $this->user)); ?>
    </section>
</article>