<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$subtitle = is_object($this->topic) ? $this->topic->getName() : NULL;
$this->renderTitle($this->translate('Themenübersicht'), NULL, $subtitle);
//$this->partial('taxonomy/default/partial', array('term' => $topic, 'children' => $topic->getChildren()))
?>
<!--
    <div>
        <?php if($this->topic->hasParent()): ?>
        <a class="btn btn-small" href="<?php echo rawurldecode($this->url()->buildWithSubject('topic', array('path' => implode('/', $this->topic->getParent()->getPath())))); ?>"><i class="icon-chevron-left"></i></a>
        <?php else: ?>
        <a class="btn btn-small" href="<?php // echo rawurldecode($this->url('subject/math/home')); ?>"><i class="icon-chevron-left"></i></a>    
        <?php endif; ?>
    </div>
-->
<?php echo $this->taxonomy; ?>
<?php echo $this->entities; ?>