<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$subtitle = is_object($this->term) ? $this->term->getName() : NULL;
?>
<h1 class="page_header"><?php echo $this->translate('Themenansicht'); ?> <small><?php echo $subtitle; ?></small></h1>
<?php echo $this->partial($this->plugin->getTemplate('taxonomy'), array('subject' => $this->subject, 'plugin' => $this->plugin, 'term' => $this->term, 'terms' => $this->terms)); ?>
<?php echo $this->partial($this->plugin->getTemplate('links'), array('links' => $this->links, 'acceptsEntities' => $this->acceptsEntities, 'subject' => $this->subject, 'plugin' => $this->plugin, 'term' => $this->term)); ?>