<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<ul>
    <?php foreach($this->terms as $term):?>
        <li class="term"
		class="<?php echo ($term->getId() == $this->plugin->getTopic()->getId()) ? '' : 'present'; ?>">
    		<div class="" style="margin: 5px 0;">
            	    <?php if ($term->linkAllowed('entities')): ?>
            		
                        <div class="right btn-group">
                        <a
                        	href="<?php echo $this->url('entity/plugin/taxonomy/update', array('action' => 'set-topic', 'entity' => $this->plugin->getEntityService()->getId(), 'term' => $term->getId() )); ?>"
                        class="btn btn-mini<?php echo ($term->getId() == $this->plugin->getTopic()->getId()) ? ' disabled' : ' '; ?>"><i
                        class="icon-map-marker"></i></a>
                        </div>
            		<?php endif; ?>
            		<div>
                        <?php echo $term->getName(); ?>
            		</div>
    		</div>
            <?php echo $this->partial('/entity/plugin/taxonomy/topic-dialog', array('plugin' => $plugin, 'terms' => $term->getChildren()->asService())); ?>
        </li>
    <?php endforeach; ?>
</ul>