<div class="page-header">
    <h1><?php echo $this->translate('Profile'); ?> <small><?php echo $this->user->getUsername(); ?></small></h1>
</div>
<?php if($this->user->getLastLogin() !== NULL): ?>
    <div class="row">
        <div class="col-md-4">
            <strong><?php echo $this->translate('Last seen'); ?></strong>
        </div>
        <div class="col-md-8">
            <?php echo $this->timeago()->format($this->user->getLastLogin()); ?>
        </div>
    </div>
    <hr>
<?php endif; ?>
<div class="row">
    <div class="col-md-2">
        <strong><?php echo $this->translate('Roles'); ?></strong>
    </div>
    <div class="col-md-3">
        <ul>
            <?php foreach($this->user->getRoles() as $role): ?>
                    <li>
                        <?php $url = $this->url('user/role/remove', array('user' => $this->user->getId(), 'role' => $role->getId()));?>
                        <?php if($this->guard()->hasAccessToUrl($url)): ?>
                            <div class="dropdown">
                                <a class="dropdown-toggle btn btn-default btn-xs" data-toggle="dropdown" href="#">
                                  <?php echo $role->getName(); ?> <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu nav nav-list">
                                    <li><a href="<?php echo $url; ?>"><?php echo $this->translate('Remove role'); ?></a></li>
                                </ul>
                            </div>
                        <?php else: ?>
                          <?php echo $role->getName(); ?>
                        <?php endif; ?>
                    </li>
            <?php endforeach; ?> 
        </ul>
    </div>
    <?php if($this->guard()->hasAccessToRoute('user/role/add')): ?>
        <div class="col-md-7">
            <div class="dropdown">
                <a class="dropdown-toggle btn btn-default btn-xs" data-toggle="dropdown" href="#">
                  <?php echo $this->translate('Add role'); ?> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu nav nav-list">
                    <?php foreach($this->user->getUnassociatedRoles() as $role): ?>
                    <li>
                        <a href="<?php echo $this->url('user/role/add', array('user' => $this->user->getId(), 'role' => $role->getId()));?>"><?php echo $role->getName(); ?></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>
</div>
<hr>
<div class="row">
    <div class="col-md-2">
        <strong><?php echo $this->translate('Activity log'); ?></strong>
    </div>
    <div class="col-md-10">
        <?php echo $this->events()->renderUserLog($this->user->getId()); ?>
    </div>
</div>