<?php
/* @var $entity \Entity\Entity\EntityInterface */
/* @var $options \Entity\Options\EntityOptions */
$entity = $this->entity;
$options = $this->entity()->getOptions($entity);

if ($this->isGranted('flag.create', $entity)): ?>
    <li>
        <a href="<?php echo $this->url('flag/add', array('id' => $entity->getId())); ?>">
            <span class="glyphicon glyphicon-flag"></span>
            <?php echo $this->translate('Flag content'); ?>
        </a>
    </li>
<?php endif; ?>