<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license	LGPL-3.0
 * @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="page-header">
	<h1>
	   <?php echo $this->translate('Unrevised learning resources'); ?><small> <?php echo $this->translate( $this->subject->getName() ); ?></small>
	</h1>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th><?php echo $this->translate('Title'); ?></th>
			<th><?php echo $this->translate('Type'); ?></th>
		</tr>
	</thead>
	<tbody>
        <?php foreach($this->entities as $entity): ?>
        <tr>
			<td><?php echo $this->normalize()->toAnchor($entity); ?></td>
			<td><?php echo $entity->getType()->getName(); ?></td>
		</tr>
        <?php endforeach; ?>
	</tbody>
</table>