<?php
/**
 *
* Athene2 - Advanced Learning Resources Manager
*
* @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
* @license	LGPL-3.0
* @license	http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
* @link		https://github.com/serlo-org/athene2 for the canonical source repository
* @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
*/
?>
<?php echo $this->partial($this->term->getTemplate('update'), array('term' => $this->term)); ?>
<script type="text/javascript">
var termsort = 
  $("#<?php echo $this->term->getId(); ?>").sortable({
	  handle: 'i.icon-resize-vertical',
	  group: 'nested',
      serialize: function ($parent, $children, parentIsContainer) {
          //var result = $.extend({id: $parent.attr('id')}, $parent.data())
          var result = $.extend({id: $parent.attr('id')}, $parent.data());
          if(parentIsContainer)
              return $children
          else if ($children[0]) 
              result.children = $children
          delete result.sortable
          delete result.subContainer
          return result
      },
	  onDrop: function (item, container, _super) {
          var dataToSend = {sortables: {id: $("#<?php echo $id; ?>").attr('data-id'), children: $("#<?php echo $id; ?>").sortable("serialize").get()}};
          console.dir(dataToSend);
          $.ajax({
              url: "<?php echo $this->url('taxonomy/term',array('action' => 'order'));?>",
              type: "post",
              data: dataToSend,
              cache: false,
              dataType: "json",
              success: function () {}
          });

		  _super(item, container)
	  },
	});
</script>