

<?php
$this->headTitle('page'.$slug);
?>


<?php // Repository Menü?>
<?php if ($this->hasRole('moderator')) echo $this->partial('page/index/repository-menu.phtml', array(
    'slug' => $slug)); ?> 


<article>
	<h1>TITEL: 
		<?php if($title!=NULL) echo $this->escapeHtml($title);?> <br>
	</h1>
    CONTENT:
	<?php if ($content!=NULL) echo $content;?>

	<br>
</article>


<?php //Revision Menü?>

<?php if ($this->hasRole('moderator')) echo $this->partial('page/index/revision-menu.phtml', array(
    'slug' => $slug,
    'id'=>$revisionid)); ?>
