

<?php
$this->headTitle('Page '.$slug.' ');
?>

<a href="<?php echo '/page/'?>">Neue Seite</a>

<a href="<?php echo '/page/'.$slug.'/editrepository'?>">Seite Bearbeiten</a>

<a href="<?php echo '/page/'.$slug.'/delete'?>">Seite Löschen</a>


<article>

		 


 Author:
	<?php $author = $revision->getAuthor(); $id = $revision->getId(); 
		 if($author!=NULL) echo $this->escapeHtml($author);?> 

 Date:
	<?php $date = $revision->getDate();
		 if($date!=NULL) echo $this->escapeHtml($date->format('Y-m-d H:i:s'));?> 
	<br>
	  <h1>Title:
	<?php $title = $revision->getTitle();
		 if($title!=NULL) echo $this->escapeHtml($title);?> 
</h1> 
	<br>
	
 Content:
    <?php $content = $revision->getContent();
		 if($content!=NULL) echo $content;?> 
	 
	
	<br>
</article>

<a href="<?php echo '/page/'.$slug.'/edit/'.$id?>">Revision bearbeiten</a>
<a href="<?php echo '/page/'.$slug.'/revisions'?>">Revisionen Verwalten</a>
<a href="<?php echo '/page/'.$slug.'/'.$id.'/delete'?>">Revision löschen</a>

<br>
