

<?php
$title2 = 'Page ';
$this->headTitle($title2);
?>

<?php //Show Repository Menu?>
<?php echo $this->partial('page/index/repository-menu.phtml', array(
    'slug' => $slug)); ?><br>
    
<?php foreach ($this->revisions as $revision) { ?>
<article>
<?php $id = $revision->getId();?>

<a href="<?php echo $this->url('page/article/revision',array('slug'=>$slug,'id'=>$id));?>" class="btn-mini btn-primary">

		 
 Title: 
	<?php $title = $revision->getTitle();
		 if($title!=NULL) echo $this->escapeHtml($title);?> 


	<?php // $author = $revision->getAuthor();
		 // if($author!=NULL) echo $this->escapeHtml($author);
		 ?> 
</a>
 Date:
	<?php $date = $revision->getDate();
		 if($date!=NULL) echo $this->escapeHtml($date->format('Y-m-d H:i:s'));?> 
	</a>
<a href="<?php echo $this->url('page/article/createrevision',array('slug'=>$slug,'id'=>$id))?>" class="btn-mini btn-info"> Revision Barbeiten</a>
<a href="<?php echo $this->url('page/article/deleterevision',array('slug'=>$slug,'revisionid'=>$id))?>" class="btn-mini btn-info"> Revision löschen</a>
	 <a href="<?php echo $this->url('page/article/revision/setCurrent',array('slug'=>$slug,'id'=>$id))?> " class="btn-mini btn-info">
	  Als Aktuelle Revision setzen
	 


	<br>
</article>

<?php } ?><br>
<a href="<?php echo $this->url('page/article',array('slug'=>$slug));?>"><button class="btn btn-mini btn-primary" type="button">Aktuelle Revision</button></a>
<a href="<?php echo $this->url('page/article/createrevision',array('slug'=>$slug,'id'=>null))?>"><button class="btn btn-mini btn-primary" type="button">Neue Revision</button></a>
<br>
