

<?php
$this->headTitle('Page '.$slug.' ');
?>

<?php //Show Repository Menu?>
<?php echo $this->partial('page/index/repository-menu.phtml', array(
    'slug' => $slug)); ?>

<article>

 Author:
	<?php $id = $revision->getId(); 
		 if($author!=NULL) echo $this->escapeHtml($author);?> 

 Date:
	<?php $date = $revision->getDate();
		 if($date!=NULL) echo $this->escapeHtml($date->format('Y-m-d H:i:s'));?> 
	<br>
	  <h1>Title:
	<?php $title = $revision->getTitle();
		 if($title!=NULL) echo $this->escapeHtml($title);?> 
</h1> 
	<br>
	
 Content:
    <?php $content = $revision->getContent();
		 if($content!=NULL) echo $content;?> 
	 
	
	<br>
</article>

 <a href="<?php echo $this->url('page/article/revision/setCurrent',array('slug'=>$slug,'id'=>$id))?>">
	 <butto class="btn btn-success" type="button"> Als Aktuelle Revision setzen </button></a>
<?php echo $this->partial('page/index/revision-menu.phtml', array(
    'slug' => $slug,
    'id'=>$id)); ?>

<br>
