<?php echo $this->pageHeader('Uuid recycle bin')->render(); ?>
<table class="table">
	<thead>
	   <tr>
	       <th><?php echo $this->translate('ID'); ?></th>
	       <th><?php echo $this->translate('Uuid'); ?></th>
	       <th><?php echo $this->translate('Type'); ?></th>
	       <th><?php echo $this->translate('Actions'); ?></th>
	   </tr>
	</thead>
	<tbody>
        <?php /* @var $entity \Uuid\Entity\UuidInterface */ ?>
        <?php foreach($this->entities as $entity): ?>
            <tr>
                <td><a href="<?php echo $this->url('uuid/router', array('uuid' => $entity->getId())); ?>"><?php echo $entity->getId(); ?></a></td>
                <td><?php echo $entity->getUuid(); ?></td>
                <td><?php echo $entity->getHolderName(); ?></td>
                <td>
                    <div class="btn-group">
                        <?php if($this->rbac()->hasAccessToRoute('uuid/restore')): ?>
                            <a class="btn btn-success btn-xs" href="<?php echo $this->url('uuid/restore', array('id' => $entity->getId())); ?>">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>
                        <?php endif; ?>
                        <?php if($this->rbac()->hasAccessToRoute('uuid/purge')): ?>
                            <button class="dialog btn btn-danger btn-xs" href="<?php echo $this->url('uuid/purge', array('id' => $entity->getId())); ?>" data-content="<?php echo $this->translate('Do you really want to purge this item? It and all references to it will be lost forever!'); ?>" data-type="danger">
                                <span class="glyphicon glyphicon-fire"></span>
                            </button>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>