<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author    Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   LGPL-3.0
 * @license   http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<?php /* @var $router \Contexter\Router\RouterInterface */ ?>
<?php $router = $this->router; ?>
<?php if ($router->hasAdapter()): ?>
    <?php if ($this->type !== NULL): ?>
        <h3><?php echo $this->translate($this->type); ?></h3>
    <?php endif; ?>
    <ul class="nav nav-pills">
        <?php /* @var $match \Contexter\Model\ContextModelInterface */ ?>
        <?php foreach ($this->matches as $context): ?>
            <li><a href="<?php echo $this->normalize()->toUrl($context->getObject()); ?>">
                    <?php echo $context->getTitle(); ?>
                </a>
            </li>
        <?php endforeach; ?>
        <?php if ($this->isGranted('contexter.context.add')): ?>
            <?php $url = $this->url($router->getRouteMatch()->getMatchedRouteName(), $router->getRouteMatch()->getParams()); ?>
            <li>
                <a href="<?php echo $this->url('contexter/add', array(), array('query' => array('uri' => $url))); ?>">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>