<footer id="footer">
    <?php
    echo $this->navigation('footer_navigation')
        ->menu()
        ->setUlClass('nav navbar-nav pull-left')
        ->setPartial('layout/navigation/footer')
        ->render();
    ?>
</footer>
<script type="text/javascript"
        src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<?php echo $this->inlineScript(); ?>