<head>
    <meta charset="utf-8">
    <?php  echo $this->headTitle($this->titleHead)->setAutoEscape(false); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <?php echo $this->headScript(); ?>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,600' rel='stylesheet' type='text/css'>
    <?php echo $this->inlineScript(); ?>
</head>