<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->brand()->getHeadTitle(true))->setSeparator(' - '); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php /* excluded for now <meta name="viewport" content="width=device-width, user-scalable=no">*/ ?>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,600' rel='stylesheet' type='text/css'>
</head>