<aside id="navigation">
    <div id="navigation-container">
        <div id="navigation-toggle" class="layout-toggle">
            <i class="glyphicon glyphicon-list"></i>
        </div>
        <?php
        echo $this->partial('layout/partials/search.phtml');

        echo $this->navigation('navigation')
                    ->menu()
                    ->setPartial('layout/navigation/side-navigation.phtml')
                    ->setOnlyActiveBranch(false)
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setUlClass('nav clear')
                    ->render();
        ?>
    </div>
</aside>