<div class="row-fluid">
    <div class="col-xs-12" id="application">
        <div class="flasher">
            <?php
            if ($this->flashMessenger()->hasSuccessMessages()) {
                echo '<div class="alert alert-success">';
                foreach ($this->flashmessenger()->getSuccessMessages() as $message)
                    echo '<p>' . $message . '</p>';
                echo '</div>';
            }
            
            if ($this->flashMessenger()->hasErrorMessages()) {
                echo '<div class="alert alert-error">';
                foreach ($this->flashmessenger()->getErrorMessages() as $message)
                    echo '<p>' . $message . '</p>';
                echo '</div>';
            }
            
            if ($this->flashMessenger()->hasMessages()) {
                echo '<div class="alert alert-info">';
                foreach ($this->flashmessenger()->getMessages() as $message)
                    echo '<p>' . $message . '</p>';
                echo '</div>';
            }
            ?>
        </div>
        <!-- <header class="page-header">
            <h1><?php echo $this->titleApplication; ?></h1>
        </header> -->
        <?php echo $this->content; ?>
    </div>
</div>