<div id="search-content">
    <input id="search-input" class="input-search" type="search" placeholder="<?php echo $this->translate('Suche'); ?>" tabindex="1"/><i class="glyphicon glyphicon-search"></i>
    <!-- tbd:search:results -->
    <!-- markup:<ul id="search-results" class="nav">
        <li><a href="#">Ergebnis oans</a>
        </li>
        <li><a href="#">Ergebnis zwoa</a>
        </li>
        <li><a href="#">Ergebnis drei</a>
        </li>
        <li><a href="#">Ergebnis vier</a>
        </li>
        <li><a href="#">...</a>
        </li>
    </ul> -->
    <div id="search-help">
        <div class="row">
            <div class="col-xs-12">
                <p>Suche zum Beispiel nach <em>Nullstellen</em>, <em>Euklidische Theorie</em>, <em>Abituraufgaben</em> oder
                    deinem <em>Bundesland</em>
                </p>
            </div>
        </div>
    </div>
</div>