<div id="search-content">
    <input id="search-input" class="input-search" type="search" placeholder="<?php echo $this->translate('Search'); ?>" tabindex="1"/><i class="glyphicon glyphicon-search"></i>
    <ul id="search-results" class="nav"></ul>
    <div id="search-help">
        <div class="row">
            <div class="col-xs-12">
                <p>Suche zum Beispiel nach <em>Nullstellen</em>, <em>Euklidische Theorie</em>, <em>Abituraufgaben</em> oder
                    deinem <em>Bundesland</em>
                </p>
            </div>
        </div>
    </div>
</div>