<div id="serlo-menu" class="navbar navbar-default">
    <nav class="navbar-inner">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <?php
                    // top left navigation
                    echo $this->navigation('top_left_navigation')
                            ->menu()
                            ->setUlClass('nav navbar-nav')
                            ->setPartial('layout/navigation/horizontal.phtml')
                            ->render();
                    // top right navigation
                    echo $this->navigation('top_right_navigation')
                             ->menu()
                             ->setUlClass('nav navbar-nav pull-right')
                             ->setPartial('layout/navigation/horizontal.phtml')
                             ->render();
                    ?>
                    <ul class="nav navbar-nav pull-right">
                        <?php echo $this->notifications()->render(); ?>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</div>